- package.json
- public/index.html
- src/docs/home.js
- src/docs/index.js
- src/docs/spec/index.js
Now that we have a better favicon, I thought it would be a good idea to have dynamic titles to pages in the documentation. So I added them via the Helmet library and they seem to work ok!
> Added dynamic titles to pages with Helmet

- src/components/atoms/_box.js
- src/components/atoms/button.js
- src/components/atoms/code.js
- src/components/atoms/input.js
- src/components/atoms/select.js
- src/components/atoms/switch.js
- src/components/molecules/form/index.js
- src/docs/spec/index.js
The docgen way of writing descriptions is to put it as a comment on top of a the React component.
Because, we already have a freeform documentation format, this felt disconnected. Description should just be the first thing you write in the doc file
> Remove description from component code

- src/components/molecules/form/form.md
You can do things like this:
```jsx
<Form.TextInput
label="Field label"
type="text"
placeholder="Enter something"
description={
<span>
Find more about it <a href="link">here</a>
</span>
}
/>
```
> Document component use in form description

- package-lock.json
- package.json
- src/components/atoms/_styled-input.js
- src/components/atoms/input.js
- src/components/atoms/select.js
- src/components/atoms/text-input.js
- src/components/atoms/text-input.md
- src/components/atoms/textarea.js
- src/components/index.js
- src/components/molecules/action-input.js
- src/docs/sidebar/search.js
- src/docs/spec/props.js
- tooling/component-metadata.js
Fixes https://github.com/auth0/cosmos/issues/64
`TextInput`, `Select`, `TextArea` now extend a common `StyledInput`
.+ renames `Input` to `TextInput`
> Pull out styled input to its own file + rename Input to TextInput

- src/components/atoms/textarea/index.js
Adding white-space: pre to this context makes it look better.
Before:
After:
> Added CSS property to display long chunks of code without word-breaks

- src/components/atoms/button/button.md
- src/components/atoms/switch/switch.md
- src/components/atoms/text-input/text-input.md
- src/components/atoms/textarea/textarea.md
- src/docs/spec/example.js
- src/docs/spec/playground.js
Multiple classnames was deprecated in `markdown-to-jsx@6`
Because of that examples with `js multiple` didn't work. Got rid of them completely, we don't really need them.
Renamed `props.tags` in playground to `props.language` because now it's only singular.
> Fix broken docs

- src/components/atoms/select/index.js
- src/components/atoms/select/select.md
Closes #180.
This also removes the `error` prop since that seems to now be a function of form components rather than the atoms themselves.
> Implemented defaultSelected on Select options, removed error prop

- src/components/molecules/list/index.js
Lesson learned: 
When iterating through children, don't use `props.children.map`, it would fail in the case when there's just one child.
Use `React.Children.map` instead.
> Fix bug in connections

- src/docs/spec/playground.js
- src/docs/spec/props.js
Added a reset for the `<pre>` tags that affect the Live preview and Props table. This is a temporary fix until we figure out https://github.com/auth0/cosmos/issues/203
> Temporary fix to reset white spce from the <pre> tags

- package-lock.json
- package.json
- src/components/atoms/button/button.md
- src/docs/spec/example.js
- src/docs/spec/index.js
- src/docs/spec/page-header.js
You can drop information at the top of the doc using [yaml](http://docs.ansible.com/ansible/latest/YAMLSyntax.html) like this: 
```meta
category: Actions
description: Buttons are great to ask users for action
```
and it will be available in the doc's [`PageHeader`](https://github.com/auth0/cosmos/compare/doc-header?expand=1#diff-ce2b0d4526663a22e8690c07c90193a5) component as props.
Check out  Button [markdown](https://github.com/auth0/cosmos/pull/222/files#diff-0497367b9a8e0c9306ebdd7854d050e5) and [docs](https://auth0-cosmos-doc-header.now.sh/docs/Button) to see an example.
The language choice is very arbitrary. I saw someone use yaml in markdown, so I started using it, we can also use json. That would look like this:
```meta
{
"category": "Actions",
"description": "Buttons are great to …
```
> Add doc page-header component

- src/components/molecules/tabs/index.js
- src/components/molecules/tabs/tabs.md
I got stuck documenting the `selected` prop. I added the `boolean` type but it looks weird as the switch doesn't do anything as it can't know which tab to activate. That made me look into other implementations where the selected tab is a `string` passed to **Tabs** (not to the single Tab) and each Tab has an `ID`. Just throwing this to see if we can solve this now, or we sit on this.
Check the deployment docs look like this:
 
> Better documentation for Tabs

- src/docs/spec/default-props.js
- src/docs/spec/playground.js
- src/docs/spec/prop-string.js
- src/docs/spec/prop-switcher.js
- src/docs/spec/props.js
This PR sets up some of the groundwork for https://github.com/auth0/cosmos/issues/231.
Thought it's worth merging on it's own as well. 
1. (Enhancement) Removes redundant `transparent={false} disabled={false} destructive={false}...` noise.
2. (Invisible) Pulls out some of the confusing functions related to prop table to their own files, making them easy to refactor
> Docs: Remove false booleans from playground

- src/components/molecules/empty-state/empty-state.md
- src/docs/spec/default-props.js
- src/docs/spec/playground.js
- src/docs/spec/prop-string.js
- src/docs/spec/prop-switcher.js
- src/docs/spec/props.js
- tooling/component-metadata.js
**Hard dependency on https://github.com/auth0/cosmos/pull/255** (Review after merging that)
Fixes https://github.com/auth0/cosmos/issues/231
&nbsp;
Part 1:
Because `react-docgen` does not evaluate `propTypes` and `defaultProps`, it results in ugly strings in the metadata
```js
name: "'copy'"
```
Added some string cleaning in `build:docs`. (Not the prettiest code, we can rid of this part after https://github.com/auth0/cosmos/issues/253)
&nbsp;
Part 2: 
Cleaned up potential cases for prop-string generation for playground. The code is now readable 🎉 and handles booleans, numbers and strings cleanly.
This is how it works:
```
Case 1: Falsy booleans:  These should be ignored: primary="false" / name="null"
Case 2: Truthy boolean: We only need to drop the key
Example: primary="true" results in …
```
> Proptable clean strings

- src/components/atoms/select/index.js
- src/components/atoms/select/select.md
- src/docs/spec/props.js
1. readOnly was not working because `{props}` was missing.
2. React was throwing a few errors at us
```
Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```
> Select: Fix readonly and default selection

- src/components/atoms/button/button.md
- src/components/atoms/button/index.js
- src/components/molecules/_action-input/index.js
- src/components/molecules/form/field/field.md
Closes #193.
This patch adds a `tooltip` prop to `Button` which, when specified, will wrap the `Button` in a `Tooltip` with the value of the `tooltip` prop as the text content. This patch also expands the action shape used in `ActionInput` (and therefore `Form.TextInput`, etc.) by adding a `label` property. If specified, the action button in the input will be rendered with a tooltip.
On a side note, I don't like what `prettier` did to this function. Yikes! I promise that my original version was much more readable. 😄 
```jsx
const ButtonContent = ({ children, ...props }) => {
if (props.icon && children)
return <ButtonWithIconAndText {...props}>{children}</ButtonWithIconAndText>
else if (props.icon && !children) return <ButtonWithIcon {...props}>{children}</ButtonWithIcon>
else return …
```
> [Button] Add support for tooltips

- src/components/atoms/text-input/text-input.md
- src/components/atoms/textarea/index.js
- src/components/atoms/textarea/textarea.md
- src/components/atoms/tooltip/index.js
- src/components/atoms/tooltip/tooltip.md
Fixes https://github.com/auth0/cosmos/issues/246 (Rollup: Documentation Tweaks)
↗️ ActionInput: Add documentation about form actions (this was added to TextInput already in #224, is that sufficient?)
> Documentation Tweaks Part 1

- src/components/molecules/form/actions/index.js
In `label-on-top`, the alignment was broken
Before:
After:
> Fix alignment for Form.Actions

- src/components/molecules/_action-input/index.js
- src/components/molecules/form/field/field.md
- src/components/molecules/form/field/index.js
Note: The separation between icons is way too big, being handled in https://github.com/auth0/cosmos/pull/213
> Add props + example for form field actiosn

- src/components/atoms/button/index.js
- src/components/index.js
- src/components/molecules/_action-input/index.js
- src/components/molecules/button-group/button-group.md
- src/components/molecules/button-group/index.js
- src/components/molecules/form/actions/index.js
- src/manage/client-list.js
- src/manage/settings.js
1. Introduce a new component `ButtonGroup` which supports `compressed` prop
2. Reduced the padding for `ButtonWithIcon` (without text)
Results:
Used it in `Form.Field` and `Form.Actions`
Using it client lists makes it slightly better than the current implementation, the one on production is also weird 😢. Should we use `compressed`  with `<Button link/>`?
> Add ButtonGroup component

- src/components/atoms/button/index.js
disabled is a state, not a appearance.
`disabled` can be used along with any appearance: `default`, `primary`, etc.
For now, I've added `opacity: 0.5` (along with `cursor: not-allowed`) as a visual cue for disabled state. We can revisit this after PoC
> Fix disabled state for Button

- src/components/atoms/_styled-input/index.js
- src/components/atoms/text-input/index.js
- src/components/atoms/textarea/index.js
Closes #243 and #244.
We may want to consider adding tokens for the font size and/or the input height, but this should suffice for now.
> Set font size of code input/textareas to 13px, force fixed height, remove white-space pre in textareas

- src/components/atoms/text-input/index.js
- src/components/atoms/text-input/text-input.md
- src/manage/settings.js
As described in #185, the use of `type=password` to hide non-password information triggers password managers like 1Password. This patch adds a prop called `masked` to the `TextInput` which will manually obscure the value, and force the input to be `readOnly`.
If we decide to go with this proposal, we should definitely test switching a managed `TextInput` between masked and "not-masked" to make sure the value isn't lost. If the component is managed (that is, the`value` comes from a parent component) it should be okay.
WDYT?
> [TextInput] Add new "masked" prop to obscure hidden data

- src/components/atoms/text-input/index.js
- src/components/atoms/text-input/text-input.md
Saw a few warnings about using value and defaultValue together after https://github.com/auth0/cosmos/pull/205
We should use just defaultValue here, right?
@nkohari Ideas?
> TextInput: should use defaultValue instead of value

- src/components/atoms/text-input/index.js
Closes #308 and #320.
Looks like the fixed height style got lost when the masked input mode was merged. This patch also makes the masked input mode use `defaultValue` for consistency's sake, but as discussed in Slack we may want to consider using `value` across the board if our goal is to work with controlled components.
> Fixes for inputs

- src/components/molecules/page-header/description.js
- src/components/molecules/page-header/index.js
- src/manage/advanced.js
- src/manage/client-list.js
- src/manage/connections.js
- src/manage/index.js
- src/manage/settings.js
Did a quick check and fixed a few visual bugs to match the original Manage design. Some will need to be reworked to avoid doing overrides on the components. But it's a good template to know what we need to enhance in the PoC via components. 
On Manage PoC:
- Fixed the Page `margin-top` to keep the Sidebar and Page Header aligned
- Removed empty form groups from the **Advanced tab** 
- Changed **Client ID** field to a code input field in **Settings**
- Adjusted **Connections table** to match original design by removing Switch Labels
- Added a quick override on the **Connections tab** for the first Paragraph -> _We need to find a better solution_
- Added margin override on the **Clients Page** for the Page Header -> _We need to find a better solution to avoid the override_
On the Page …
> Polish sections of the PoC

- src/components/atoms/_box/index.js
- src/components/atoms/avatar/avatar.md
- src/components/atoms/button/button.md
- src/components/atoms/code/code.md
- src/components/atoms/heading/heading.md
- src/components/atoms/icon/icon.md
- src/components/atoms/link/link.md
- src/components/atoms/logo/logo.md
- src/components/atoms/overlay/overlay.md
- src/components/atoms/paragraph/paragraph.md
- src/components/atoms/switch/switch.md
- src/components/atoms/text-input/text-input.md
- src/components/atoms/textarea/textarea.md
- src/components/index.js
- src/components/molecules/button-group/button-group.md
- src/components/molecules/form-group/form-group.md
- src/components/molecules/form/form.md
- src/components/molecules/list/list.md
- src/components/molecules/page-header/page-header.md
- src/components/molecules/stack/stack.md
Closes #382.
We may want to change this in the future, but this updates the docs to (I believe?) the correct import syntax.
> Updated import statements in docs to reflect the current package name in npm

- src/components/atoms/button/button.md
- src/components/atoms/button/index.js
- src/components/atoms/tooltip/index.js
- src/components/atoms/tooltip/tooltip.md
- src/components/molecules/button-group/button-group.md
- src/components/molecules/dialog/index.js
- src/components/molecules/empty-state/index.js
- src/components/molecules/form/actions/index.js
- src/docs/home.js
- src/docs/spec/prop-string.js
- src/overview/examples/buttons.js
- src/overview/src/buttons.js
Closes #364.
Related to #88.
This patch combines the `default`, `primary`, `transparent`, `link`, and `destructive` props on `Button` into a single enumeration called `intent`. The name of this prop is debatable; there were several suggestions, so I just picked one that was more descriptive than `type`. 😄 
The `disabled`, `loading`, and `success` props are left as Booleans, and they influence (or override) the styles set by intents. It's still technically possible for these state-oriented properties to collide, but it's reasonable to have a combination of two. For example, you might want to disable a button while a form is saving, so you might set it both `disabled` and `loading`.
In `Tooltip`, the `top` and `bottom` props are combined into a `position` enum. We could just eliminate the …
> Replaced colliding Booleans with enums in Button and Tooltip

- src/components/_helpers/reset.js
- src/components/molecules/form/description.js
- src/components/molecules/form/field/field.md
- src/components/molecules/form/field/index.js
- src/components/molecules/form/form.md
- src/components/molecules/form/help-text.js
- src/manage/pages/client-detail/advanced.js
- src/manage/pages/client-detail/settings.js
- src/manage/pages/clients/create-client-dialog.js
- src/overview/examples/forms.js
- yarn.lock
Closes #365.
This was already unofficially supported, so this patch just removes the warning and updates the docs. There's still an unanswered question on the issue regarding whether we want to continue supporting backticks in strings, but this can be merged either way.
> Allow form field description (helper text) to accept React components

- src/components/atoms/button/button.md
- src/components/atoms/button/index.js
- src/components/molecules/empty-state/index.js
- src/components/molecules/page-header/index.js
Closes #417.
This patch adds a `size` prop to `Button`, which controls the vertical height and horizontal padding of the button. Also, the branching logic in `Button` was quickly turning to spaghetti so I took a stab at simplifying it. In addition to (hopefully) making the code easier to understand, this should also fix some bugs with edge cases; for example, previously setting a button with only an icon to `success` would cause it to gain a minimum width and horizontal padding.
I also added the new large button to `PageHeader` and `EmptyState`. I think we probably want the `small` button inside of the clients table in the example app, but I wasn't sure.
> Add size prop to Button

- .travis.yml
now-cd now supports aliases: https://github.com/siddharthkp/now-cd/pull/10
With our new release process, `stable` should point to production instead of master
> Stable points to production

- changelog.md
- src/docs/changelog.json
- src/docs/changes.js
- src/docs/index.js
- src/docs/sidebar/list.js
- tooling/component-metadata.js
Closes #361.
This patch adds a `changelog.md` file to the root of the repo, which should be kept up-to-date with important PRs that are merged. If you know you're introducing a significant addition or change (especially breaking changes) it's probably a good idea to update the changelog in the commit itself. Before we ship new versions we should always do a final pass to ensure the changelog contains all the things we want to highlight.
The contents of the changelog is also added to the docs at `/docs/changes`. Right now, I added a (rather hacky) step that reads the contents of `changelog.md` and writes it to `src/docs/markdown.json` so it can later be read by `markdown-to-jsx` -- basically the same thing that the component documentation does now.
I started getting a little too fancy with …
> First pass at a changelog

- examples/perf-tests/package.json
- examples/perf-tests/webpack.config.js
- examples/webpack-hello-world/package.json
- examples/webpack-hello-world/webpack.config.js
- src/components/babel.js
- src/components/package.json
- tooling/catchup.js
- tooling/publish.js
Now that we transpile components by default, we don't need to ship the babel-preset by default.
It will also not end up in the product's lock file, [example](https://github.com/auth0/manage/pull/3769#discussion_r179614332)
> Make preset optional

- src/components/atoms/tooltip/tooltip.md
- src/docs/spec/get-defaults-from-code.js
- src/docs/spec/playground.js
- src/docs/spec/props.js
Fixes: https://github.com/auth0/cosmos/issues/259 and https://github.com/auth0/cosmos/pull/491
Syntax:
```jsx
<Tooltip {props} defaults={{content: "Here is some text"}}>Hover me</Tooltip>
```
The code is mostly garbage. I wouldn't suggest reviewing it, we need a rewrite of playground section of the docs
With some magic, it pulls it from the code and passes it to props.
> Add ability to add defaults for prop table example

- src/manage/components/page.js
- src/manage/components/side-navigation.js
- src/manage/pages/anomaly-detection/index.js
- src/manage/pages/apis/index.js
- src/manage/pages/clients/index.js
- src/manage/pages/rules/index.js
- src/manage/pages/slogs/index.js
- src/manage/pages/sso-integrations/index.js
- src/manage/pages/users/index.js
Added routing and stub pages for many sections of the PoC to test out components will real data and in a product context. This will also allow us to try mix and matching components in different situations. 
At first glance I think we can try and avoid having styled-components included in these pages so we can check the flexibility (or lack of) Cosmos components. Should we need to override something, we need to ack what's the proper way.
> Added additional pages to the PoC to be able to test components

- src/components/molecules/button-group/index.js
Fixes https://github.com/auth0/cosmos/issues/525
Story time
`Form.Actions` uses `ButtonGroup`
`ButtonGroup` likes it's children to be a React element or an array of them
```js
ButtonGroup.propTypes = {
children: PropTypes.oneOfType([
PropTypes.element, // just one button for dynamic cases like Form Actions
PropTypes.arrayOf(PropTypes.element)
])
}
```
Bad things happen when we have nothing to render, short version:
```jsx
<ButtonGroup>
{ props.primaryAction && <Button/> }
{ props.secondaryActions && <Button/> }
{ props.destructiveActions && <Button/> }
</ButtonGroup>
```
In some cases, this can result in `children` to be `[React.element, undefined, undefined]` and it throws a warning because `undefined != PropTypes.element`
The ideal fix for me would be to replace undefined with …
> Fix persistent warning in Form.Actions

- src/components/atoms/switch/switch.js
The matching id for label wasn't attached
> Add missing id to switch (accessibility)

- src/components/atoms/tooltip/tooltip.js
```jsx
<Tooltip position="top" content="Copy" defaultVisible>
```
Motivation to add: So that I can create a sketch component for it. Made it public because I think it's probably useful.
> Add prop to make tooltips visible by default

- src/components/atoms/radio/radio.js
- src/components/molecules/form/form.md
- Fixes https://github.com/auth0/cosmos/issues/580
`child.type === RadioOption` only works in dev, because `RadioOption` gets compiled to `React.createElement`. This check seems to be a validation on the children and we probably don't need it there. @beneliflo @nkohari can confirm?
- Fixes https://github.com/auth0/cosmos/issues/578
fixed syntax error
> Fix radio bugs

- src/components/atoms/tooltip/tooltip.js
- src/components/atoms/tooltip/tooltip.md
This adds support for the `left` and `right` values to the `position` prop of `Tooltip`.
We should consider whether we want to change from `defaultVisible` and the `&:hover` class to a `visible` prop to support a controlled version of the component.
> Add support for left and right positions to Tooltip, code cleanup

- src/components/molecules/stack/stack.js
It works the same as `fill` but without setting flex to 1
> Stack: Add space-between justifyContent prop value

- src/components/molecules/page-header/page-header.js
- src/components/molecules/page-header/page-header.md
- src/components/molecules/page-header/page-header.story.js
We now display the secondary action even if the primary one is missing.
Added two new stories:
- just renders the primary button in the Page Header to test this use case
- just renders the secondary button in the Page Header to test this use case
Resolves #589
> Page Header: show secondary action when primary is missing.

- src/components/package.json
`sideEffects: false` helps webpack 4 to tree shake the output
Right now, we do have side effects in the form of global resets. This means we can't enable tree shaking right away.
> Remove sideEffects from package.json

- src/manage/components/client-list.js
`manage/ClientList` doesn't accept props, so it doesn't need prop validations
> Remove prop types from manage/ClientList

- package.json
I was accidentally deploying *.sketch.js files to `auth0-cosmos.now.sh/sandbox`
This should fix it
> Sandbox: Deploy *.stories.js not *.sketch.js

- src/components/molecules/tabs/tabs.js
- src/components/molecules/tabs/tabs.md
This PR enables a controlled state mode in `Tab`. It will enable the users to enforce a selected index by passing a `selected` prop and subscribe to tab change intents from the user with the `onSelect` prop.
Resolves #579.
> Tabs: Add tab controlled state mode

- src/components/atoms/tooltip/tooltip.js
- src/components/molecules/button-group/button-group.js
Temporally disabling last/first child margin reduction until better solution is found.
Resolves #517
> Align tooltip on button groups.

- .gitignore
- package.json
- src/components/package.json
- tooling/component-metadata.js
- tooling/publish.js
- yarn.lock
This takes the work done in #628 and moves it to the component metadata build step, so we can consume the TypeScript defs during development and not have to wait until we publish.
> Add support for TypeScript generation (via @jcenturion)

- internal/docs/spec/prop-string.js
Supercedes #633. Since I did an interactive rebase and squashed the commits from the `avatar-block` branch, it was easier just to cherry-pick the single commit (e1ebff49e2616e8a6f9438bb7b2bf7c861f5e8d6) from the original PR branch.
> Fix avatar props in docs issue (via @francocorreasosa)

- internal/docs/app.js
Fixes https://github.com/auth0/cosmos/issues/664
Makes the sidebar collapsable under `800px` width
> Make the sidebar foldable

- internal/docs/sidebar/index.js
Our search was slightly silly.
I could never find `Form` by typing `form`. Fixed that now.
```diff
- component.displayName.includes(query)
+ component.displayName.toLowerCase().includes(query.toLowerCase())
```
> Docs: Make search case insensitive 

- core/components/_helpers/custom-validations.js
- core/components/atoms/_styled-input/_styled-input.js
- core/components/atoms/text-input/text-input.js
- core/components/atoms/textarea/textarea.js
- core/components/molecules/form/field/field.js
- core/components/molecules/form/field/field.md
Fixes https://github.com/auth0/cosmos/issues/680
Components that use `_styled-input` (`TextInput`, `TextArea`, etc.) now accept a new prop: 
`hasError: Proptypes.bool`
They continue to support `error: Proptypes.string` as well but throw a validation warning 
_'error' prop has been deprecated. Use 'hasError' instead_
The intention is to do a smooth deprecation by supporting both for a while. I've also added a new `deprecate` helper in [custom-validations](https://github.com/auth0/cosmos/blob/master/core/components/_helpers/custom-validations.js)
> Replace input error prop with hasError

- core/engine/configs/webpack.dev.config.js
- core/engine/package.json
- core/engine/utils/prop-type-errors.js
- yarn.lock
Fixes https://github.com/auth0/cosmos/issues/671 (partially)
If you don't have the console open, you might miss validation issues (because `prop-types` don't throw errors out loud)
Take this button example, when you type `danger` instead of `destructive`:
----
1. It adds an error overlay (the one from create-react-app) so you don't miss any errors.
2. Converts prop-type warnings to errors (in dev environment)
Now, when you make the same mistake, cosmos fails fast and early.
----
1. However, the problem at hand is not fully solved. In some cases incorrect props completely break cosmos and the error stack is very crowed.
Validation errors get lost in the crowd. Ideas welcome!
2. The call stack is not very helpful because it shows where was the error thrown from (our code) instead of where …
> Engine 0.2: Add error overlay

- core/components/_helpers/globals.js
- internal/docs/usage.js
By default `cosmos` will add the resets. This let's us have a out of the box setup.
You can disable the resets by passing information via webpack
```js
{
plugins: [
new webpack.EnvironmentPlugin({
COSMOS_DISABLE_RESETS: true
})
]
}
```
Added this to docs as well
> Add option to disable globals

- core/components/_helpers/action-shape.js
- core/components/molecules/form/actions/actions.js
- core/components/molecules/form/actions/actions.md
Fixes https://github.com/auth0/cosmos/issues/665
Added additional `props` prop that is forwarded to the `Button` component
```jsx  
<Form.Actions
primaryAction={{ label: 'Save Changes', props: { disabled: true }, handler: () => {} }}
/>
```
Does this API look a little wonky? Should we use a more explicit name like `extraProps` or `buttonProps`?
&nbsp;
Demo: [form-actions#passing-button-props](https://auth0-cosmos-form-actions-pass-props-through.now.sh/#/component/form-actions#passing-button-props)
There is little scope for misuse here, the `appearance` property comes after the spread props which means it will override it even if someone tries to pass `appearance="primary"` in a destructive action
```jsx
<Button {...destructiveAction.props} appearance="destructive" …
```
> Form actions pass props through

- core/components/_helpers/story-stack.js
- core/components/atoms/text-input/text-input.js
- core/components/atoms/text-input/text-input.story.js
- internal/docs/overview/examples/buttons-inputs.js
Closes #707.
This patch adds a `size` prop to `TextInput` which supports `default`, `large`, `small`, and `compressed` sizes that match those used in `Button`.
I also updated the `Stack` used in Chromatic tests in this patch, so it's possible there may be a few unexpected changes.
> Add support for size prop to TextInput

- core/components/molecules/resource-list/item/item.js
- examples/manage/components/top-navigation.js
- examples/manage/pages/apis/index.js
- examples/manage/pages/application-detail/advanced.js
- examples/manage/pages/application-detail/connections.json
- examples/manage/pages/rules/index.js
- examples/manage/pages/users/index.js
Fix PoC code where props were not passed correctly
`+`
Changed the `propTypes` for `ResourceList.Item`: 
```diff
/** An image URL to display as a thumbnail image for the list item. */
- image: PropTypes.string,
+ image: PropTypes.oneOfType([PropTypes.string, PropTypes.element])
```
This is how the PoC uses it, not sure if this is something we want to support though
@nkohari 👋
> Manage PoC: fix all prop warnings

- core/components/molecules/tabs/tabs.js
- core/components/molecules/tabs/tabs.md
- core/components/molecules/tabs/tabs.story.js
This will avoid having `shouldComponentUpdate` logic in the Cosmos internals. Handing over that responsibility to the Cosmos user.
Resolves #754
> End support for uncontrolled state in Tabs

- .prettierrc
- package.json
This PR replaces the command line interface parameters to `prettier` in favor of a `.prettierrc` file that also allows IDE plugins like the one in Visual Studio Code to read our Prettier settings and format appropriately on save (if set).
> Proposal: Use standard prettier config to improve IDE plugin compatibility.

- core/components/molecules/form/actions/actions.js
Fixes https://github.com/auth0/cosmos/issues/742 
We need this for releasing 0.3.3 (introduced in https://github.com/auth0/cosmos/issues/665)
`delete props.label`
> Remove label from button props in actions

- changelog.md
- package.json
- tooling/publish.js
There are 2 breaking changes: 
- **BREAKING**: Use `color` name instead of hex codes for `Icon` [#684]
- **DEPRECATED**: Replace input `error` prop with `hasError` [#690]
> Prepare for 0.3.3

- core/components/atoms/button/stories/wrapping.story.js
Following up from #740, this patch adds some visual tests to exercise the button wrapping logic.
> Add test to ensure buttons flow to next line, but their contents doesn't

- core/components/_helpers/action-shape.js
- core/components/molecules/form/actions/actions.js
Question: In case a handler is still provided, should we automatically `preventDefault` so the form would not submit?
> Do not require form's primary action handler

- .travis.yml
we update our deps on master after publishing
so https://auth0-cosmos-master.now.sh/docs shows 0.4.0 but deployed version shows the previous one
Running catchup before now-cd should fix it
> Website: Fix nav version in navigation 

- core/components/atoms/alert/alert.js
- core/components/atoms/text-input/text-input.js
- internal/docs/docs-components/tag.js
- internal/docs/spec/props.js
Fixed https://github.com/auth0/cosmos/issues/789
Syntax: Start the comment with `@deprecated`
```js
/** Pass hasError to show error state */
hasError: PropTypes.bool,
/** @deprecated Pass error string directly to show error state */
error: PropTypes.string
```
```js
/** @deprecated Details */
text: PropTypes.oneOfType([PropTypes.string, PropTypes.node])
```
> Add deprecated tag in docs

- core/babel-preset/dev.js
Adding [`babel-plugin-styled-components`](https://github.com/styled-components/babel-plugin-styled-components) removed `sc-` classes in dev mode. This is a problem because dev and prod should look the same, otherwise we don't know what we're shipping
We rely on these classes to set `line-height` in [globals](https://github.com/auth0/cosmos/blob/master/core/components/_helpers/globals.js#L98)
We'll have first find a better way of targeting cosmos components before bringing this plugin back
> Disable babel-sc plugin until we fix targetting problem

- core/components/molecules/tabs/tabs.js
Fixes: https://github.com/auth0/cosmos/issues/896
Checked this in the PoC (which has styleguide as the base global styles)
**Before:**
**After:**
> Added color for hover on the selected tab

- core/components/atoms/icon/icon.js
Both the `i` container and `svg` now have width and height props
> Enforced icon size to fix icon vertical alignment

- .travis.yml
- internal/docs/docs-components/navigation.js
- internal/docs/docs-components/version-switcher.js
It relies on a standard alias to exist:
`auth0-cosmos-{version}.now.sh`
example: `auth0-cosmos-0-5-2.now.sh`
> Docs: Add version switch

- internal/docs/docs-components/navigation.js
- internal/docs/docs-components/version-switcher.js
Improved the switcher to be more prominent :)
> More prominent version switcher for docs

- core/tokens/colors.js
Since secondary button's border was too light and therefore did not play well with some grey backgrounds, as suggested I have made the border darker.
fixes #823
> Made secondary button's border darker

- core/components/molecules/tabs/tabs.js
- internal/test/unit/__snapshots__/tabs.test.js.snap
The Tabs can now be navigated using the keyboard by hitting tab
Fixes: https://github.com/auth0/cosmos/issues/923
[x] tests passes
> Add accesibility to Tabs

- internal/docs/app.js
- internal/docs/sidebar/index.js
This PR fixes a scrolling bug in the sidebar, it now works as expected in Firefox:
> Fix sidebar scrolling in Firefox (fixes #994)

- core/components/atoms/alert/alert.js
Addresses the issue: "Match Alert close button to styleguide #942" by setting the close icon to 20% opacity and black with 50% opacity on hover.
> Match alert close button styling to styleguide - Issue #942

- core/components/molecules/table/table.js
- core/components/molecules/table/table.story.js
Now you can store all the columns in a variable and pass that children as a variable, albeit as first-child only. Fixes- #893 
```jsx
const defaultItems = [
{
name: 'Harry Kane',
goals: 6,
assists: 0,
country: '🇬🇧',
image: 'https://twitter-avatar.now.sh/HKane'
},
{
name: 'Romelu Lukaku',
goals: 4,
assists: 1,
country: '🇧🇪',
image: 'https://twitter-avatar.now.sh/Romelu_lukaku9'
},
{
name: 'Antoine Griezmann',
goals: 4,
assists: 2,
country: '🇫🇷',
image: 'https://twitter-avatar.now.sh/AntoGriezmann'
},
{
name: 'Ivan Perišić',
goals: 3,
assists: 1,
country: '🇭🇷',
image: 'https://twitter-avatar.now.sh/ivanperisic44'
}
]
const columns = (<div>
<Table.Column field="image" width="50px">
{item => <Avatar type="user" image={item.image} />}
</Table.Column>
<Table.Column field="name" title="Name" …
```
> Table columns can now be passed as external children

- core/components/_helpers/story-example.js
While working on https://github.com/auth0/cosmos/pull/955, I found that our tests setup also get the sc^ hack because it is built with styled-components
Any components inheriting line-height will take the wrapper's line-height. This makes our tests less reliable as the components might not behave the same way in a different environment (like styleguide)
This is how our components look outside of cosmos right now
I'm resetting the line-height in the story wrapper to inherit to establish a new source of truth for tests in #955 (where I'm fixing them)
For other PRs, you might want to back merge for best results
> remove line height in example

- core/components/molecules/pagination-toolbar/pagination-toolbar.js
> Hide pagination toolbar if 1 or zero pages (or zero items)

- core/components/molecules/tabs/tabs.js
Added some custom and subtle focus styles for the tab element. Would like to do a 2nd iteration with some less subtlety. More than nothing, this was an excuse to see if the following notation for conditional CSS is more clear or not. the new one is longer cause it has more styles (for focus and active).
**Old:**
```js
export const TabLink = styled.a`
display: inline-block;
padding: ${spacing.small} 0;
margin-right: ${spacing.large};
color: ${props => (props.selected ? colors.text.default : colors.link.default)};
cursor: ${props => (props.selected ? 'default' : 'pointer')};
border-bottom: 1px solid ${props => (props.selected ? colors.base.text : 'transparent')};
margin-bottom: -1px;
&:hover {
color: ${props => (!props.selected ? colors.link.defaultHover : colors.text.default)};
}
`
``` …
> Tabs focus styles

- core/engine/configs/webpack.production.config.js
```diff
// core/engine/configs/webpack.production.config.js
- mode: 'development'
+ mode: 'production'
```
> Build scripts should use production mode

- core/components/molecules/page-header/page-header.js
- core/components/molecules/page-header/page-header.story.js
Now the component from page header has an optional subtitle option which
creates a gray text next to the component name. As expected in the
contribution guideline the story to this new feature is now on.
Resolves: #1004
> feat: Added subtitle to page-header component

- core/components/_helpers/default-prop-change.js
> Make default prop change warning to appear if there is not a value set for the prop

- internal/docs/sidebar/list.js
Removed the Overview and Playground links from the Docs sidebar.
> Docs: Removed links that can be found in the Top navigation

- examples/manage/pages/application-detail/settings.js
When i went to application detail, it was showing me an error screen
it was because the `Form.Select` was missing a prop, so i added and now the example view works fine
> Fix applications details warning to be thrown by a missing prop

- core/components/package.json
- package.json
- tooling/component-metadata.js
This is a temporal _solution_. 
I want to make a manual typing proof of concept anytime soon, which involves adding a TypeScript compilation pipeline to Cosmos.
Related to #1131 (but does not resolves it)
> Remove prop-types to typescript declarations module

- internal/docs/docs-components/code-block.js
- internal/docs/sidebar/index.js
- internal/docs/spec/playground.js
Addresses: https://github.com/auth0/cosmos/issues/1166
I've tried added the container styles to the affected components, but I'm not sure if this is the answer for this situation. Should we just declare the line-height here, without the helper?
@siddharthkp 	can you check it out?
> Applied container styles to Sidebar, Codeblock and Playground

- core/components/atoms/button/button.js
This PR fixes #1164 by removing the unnecesary `display: table` on anchor btns.
@siddharthkp I tested it as far as I could, and I think it's ok, can you take another look at it on the usecases described on the issue please?
> Fixes anchor buttons

- internal/docs/changes.js
Closes #1124 
Here's how it looks now:
> Convert GitHub handles in changelog to link to GitHub profiles

- internal/docs/changes.js
Thanks to @tsriram
Original message:
----
Closes #1124 
Here's how it looks now:
> Changelog: Convert github handles to links by @tsriram

- internal/docs/app.js
- internal/docs/docs-components/folding-section.js
- internal/docs/guides.js
- internal/docs/pages/contribution-guide.js
- internal/docs/pages/overriding-components.js
- internal/docs/pages/usage.js
- internal/docs/pages/usage/custom-components.js
- internal/docs/pages/usage/installation.js
- internal/docs/pages/usage/using-components.js
- internal/docs/pages/usage/with-styleguide.js
- internal/docs/sidebar/list.js
1. Now you have to add a page only to this file: https://github.com/auth0/cosmos/blob/e7325d4ee5cd7e3ae3985c95528a6c1c3be9ed65/internal/docs/guides.js
2. Split usage into sections
> Docs: Make it easier to add a guide

- internal/docs/spec/props.js
- tooling/component-metadata.js
Closes #676 
I'm not sure if this is the right way to do. I thought it's better not to have `children` prop in generated metadata than skipping the `children` prop in `Props` component's loop. Let me know if you want to handle this differently. Or feel free to close this if it's not required :)
> Do not show `children` props table

- core/components/molecules/pagination-toolbar/pagination-toolbar.md
Table example had suboptimal column widths:
**Before**
**After**
---
Resource List example was giving a deprecation warning. Changed example to use recommended syntax.
> Improved examples in Pagination toolbar docs

- .storybook/config.js
- internal/cosmos-scripts/task.js
- internal/test/chromatic.js
- internal/test/package.json
- package-scripts.js
- package.json
- tooling/chromatic.js
- yarn.lock
1. This PR adds `--auto-accept-changes` to the chromatic call for master builds.
2. Moves all the logic around chromatic to a script inside `internal/test`
The logic around when the run chromatic was getting a bit complex for a single line. This should make it more reliable and easier to change (check out the script)
```diff
- if [ $TRAVIS_EVENT_TYPE != "pull_request" -o "$TRAVIS_PULL_REQUEST_SLUG" != "$TRAVIS_REPO_SLUG" ]; then chromatic test --app-code=wuz4h54syum --storybook-addon --script-name=sandbox --exit-zero-on-changes; fi;
+ cd internal/test && yarn test-visual
```
> Tooling: Auto accept chromatic builds on master

- core/components/molecules/form-group/form-group.js
> Fix FormGroup warning when only one child is passed

- core/components/atoms/_overlay/overlay.js
This Pr fixes #1224 by removing pointer events from the overlay.
> Removes pointer events on the overlay component

- core/components/_helpers/component.story.js
- core/components/styled.js
This brings back `styled.div.attrs` and `styled.div.withConfig` that were deprecated in 0.10.0
Found an easy way to implement them 😄
> Implement attrs to styled API

- core/components/atoms/switch/switch.js
I have reworked over #1273. Instead of using an array to order elements I explicitly order the elements surrounding them by fragments assigning them to the elements variable.
> Explictly declare element ordering in switch

- examples/manage/package.json
Was getting some fiber errors on manage example, turns out the versions were out of sync
> Examples: react + react-dom should have same version

- core/components/atoms/text-input/text-input.js
The code had some confusing duplication. Hope this doesn't break it.
There should be zero chromatic changes
Dependency for https://github.com/auth0/cosmos/pull/1281
> Internal: Clean up code for masked TextInput

- core/components/_helpers/component.story.js
- core/components/atoms/button/button.js
- core/components/atoms/heading/heading.js
- core/components/atoms/select/select.js
- core/components/atoms/text-input/text-input.js
- core/components/atoms/textarea/textarea.js
`styled-components@3.4.10` introduced a soft deprecation warning (like we do) for using `.extend`
Replacing the places we use `Component.extend` with `styled(Component)`
> Internal: Replace extend with styled

- core/components/molecules/page-header/description.js
- core/components/molecules/page-header/page-header.js
This PR fixes #1226 
It move the component from grid to flex so it doesn't render the grid gap and removes the node when it has no content.
> Changes the Page Header from grid to flex

- core/components/atoms/select/select.js
If a user clicks on the icon on the select, the select doesn't open.
This PR removes pointer events on the icon to fix the problem
> Select: Removes pointer events on the icon

- core/components/molecules/table/table-header.js
- core/components/molecules/table/table.js
This PR fixes #1231 by removing the line-height declaration from `th` and `td`s
It also cleans the CSS by avoiding the use of shorthands on `background`.
> Removes line height declaration on tables

- core/components/atoms/tooltip/tooltip.js
This PR solved part of the issues we have on tooltips appearing behind other elements.
Fixes #1307
> adds z-index to tooltips

- core/components/molecules/tabs/tabs.js
- internal/test/unit/__snapshots__/tabs.test.js.snap
Seems like an honest mistake
```diff
- aria-labelledby="tabs-first-tab"
+ aria-labelledby="tabs-first"
```
Demo: [auth0-cosmos-alt-unique-id/sandbox/tabs](https://auth0-cosmos-alt-unique-id.now.sh/sandbox/?selectedKind=Tabs&selectedStory=default&full=0&addons=1&stories=1&panelRight=0)
> Quick aria labels fix for Tabs

- core/components/atoms/link/link.js
- internal/docs/pages/automation-glossary.js
- internal/docs/pages/contribution-guide.js
- internal/docs/pages/contribution-guide/order-of-props.js
Sorry I wrote an essay
tl;dr: found a bug, fix means breaking change, we might be able to squeeze this in in without breaking anything
&nbsp;
---
&nbsp;
&nbsp;
When you render
```jsx
<Breadcrumb>
<Breadcrumb.Link>Home</Breadcrumb.Link>
<Breadcrumb.Link>Parent</Breadcrumb.Link>
</Breadcrumb>
```
These are the cosmos-key it renders:
```html
<div data-cosmos-key="breadcrumb">
<a data-cosmos-key="link">Home</a>
<a data-cosmos-key="link">Parent</a>
</div>
```
There are 2 problems with the `data-cosmos-key` of the child being `link`:
1. It seems to rely on an implementation detail - the breadcrumb uses a `Link` component today, this might change (maybe to `<Button appearance="link">` 🤷‍♀️)
2. This is not what the code says! The code says `breadcrumb.link`
```jsx
const Breadcrumb.Link = props => …
```
> Breadcrumb: Fix automation attribute?

- core/components/atoms/radio/radio.js
Resolves #1379 
--
We didn't need to pass the `onChange` function to every radio option.
> Fix Radio onChange callback firing twice

- core/components/_helpers/globals.js
Fixes https://github.com/auth0/cosmos/issues/1402
Browser compatibility for:
Tested for IE11, Edge 18, Firefox latest, Chrome latest, Safari latest on browserstack
> use insertBefore instead of prepend

- core/components/atoms/switch/switch.js
This PR introduces 2 changes:
- It makes the switch have a consistent width by overlapping the on and off states.
- It removes a style related JS vars in favor to a CSS var.
It'll allow better use of the switch component within layouts.
There are no changes on the API but since it's using a CSS var it's not supported by IE11.
> Makes the switch have a consistent width

- core/components/_helpers/dom.js
- core/components/_helpers/globals.js
- core/components/components.js
- core/components/index.js
SSR is currently broken because we're making use of `document` to include the style resets that cosmos requires.
To solve that problem my approach was to add a flag to avoid the automatic inclusion of styles in the Document and to export the minimum and recommended resets so they can be applied differently according to the platform.
Example:
```js
// with COSMOS_MANUAL_RESETS=true
import { resets } from '@auth0/cosmos'
insertDifferentlyAtHead(resets);
// or for Next.js
export default () => (
<div>
<style jsx global>{resets}</style>
</div>
)
```
Let me know if you think the approach makes sense! 🙂 
(I know some naming, export/import decisions are debatable, please comment if you disagree with them)
#971 
To have SSR
⚠️ Not tested yet
> Fix SSR (#971)

- core/components/atoms/select/select.js
- core/components/atoms/select/select.story.js
Fixes #1444 
This is now possible:
```jsx
class SelectWithEmptyString extends React.Component {
constructor(props) {
super(props)
this.state = { value: 'custom' }
this.handleValue = this.handleValue.bind(this)
}
handleValue(event) {
this.setState({ value: event.target.value })
}
render() {
return (
<Select
options={[
{ text: 'All apps', value: '' },
{ text: 'Custom apps', value: 'custom' },
{ text: 'Private apps', value: 'private' }
]}
value={this.state.value}
onChange={this.handleValue}
/>
)
}
}
```
> Allow using empty string as a Select value

- core/components/molecules/sidebar/sidebar-link-group.js
Do not paint current sidebar linkgroup item link when the linkgroup is open but no subitem is selected.
> Fix sidebar linkgroup item colored when open but no subitems selected

- internal/docs/sidebar/list.js
As agreed with @andresgalante, we're moving layouts to the top of Atoms and Molecules in the docs sidebar.
> Move layouts to top in docs sidebar

- core/components/atoms/switch/switch.js
- core/components/atoms/switch/switch.md
- core/components/atoms/switch/switch.story.js
- internal/docs/pages/migration-guide.js
- internal/test/integration/atoms/switch.fixture.js
- internal/test/integration/atoms/switch.test.js
```diff
- <Switch onToggle={value => console.log(value)} />
+ <Switch onChange={value => console.log(value)} />
```
soft deprecation as usual.
[why?](https://sid.studio/post/name-behaviors-not-interactions/)
Have not updated updated other components that use it. Will do that after this PR is merged/approved. (it's backward compatible)
> Switch: change onToggle to onChange

- core/components/atoms/checkbox/checkbox.js
- core/components/atoms/checkbox/checkbox.story.js
The checkbox doesn't render the colors for `readOnly`. As a simple fix I've just reduced the opacity of the checkmark.
This PR fixes this bug on Manhattan:
> [BUG] Connections: Social connections-> Any provider. Even when a permission such as "Basic Profile" and "Extended Profile" (in the case of google) are required, the checkboxes look blue like if I could click on them, but I can't.
> Improves read only checkbox styles

- core/components/atoms/_input-with-actions/input-with-actions.js
- core/components/atoms/textarea/text-area.story.js
This PR adds a space on text areas with icons, so the text doesn't run under the icon.
> Adds a space when there are icons on a textarea

- core/components/molecules/form/field/field.js
Remove this prop type assertion error when using Components as actions in Form fields.
> Fix field actions prop type to support raw buttons

- core/components/atoms/alert/alert.md
The Alert is stable, so I'm removing the alert banner so that users know it's safe to use.
> Removed unstable tag to alerts

- changelog.md
- core/babel-preset/package.json
- core/components/package.json
- core/tokens/package.json
- examples/manage/package.json
- examples/perf-tests/package.json
- examples/webpack-hello-world/package.json
- internal/cosmos-scripts/package.json
- internal/docs/package.json
- package.json
> Release 0.23.1

- core/components/atoms/image/image.md
- core/components/layouts/column-layout/column-layout.md
- core/components/layouts/row-layout/row-layout.md
In this pull request I fixed a simple spelling error in layouts and image.md for "Accessibility" from "Accecibility".
Please let me know if you have any questions, thanks!
> Fixed accessibility spelling error in layouts and image.md

- core/components/atoms/link/link.md
This is an small fix on the docs for Links. The import line is importing a Button not a Link
> Fixed example code

- core/components/atoms/link/link.md
via @tehsis 
This is an small fix on the docs for Links. The import line is importing a Button not a Link
> Fixed example code (#1588)

- internal/docs/guides/contribution-guide/system-guidelines.js
Until we implement the token system, let's remove the guidelines
> Removes tokens definitions on the guidelines

- core/components/molecules/pager/pager.md
- core/components/molecules/pager/pager.story.tsx
- core/components/molecules/pager/pager.tsx
> Same as #1603 but with working branch name.
Previously, passing page=1, perPage=50, items=0 would still let the next page button to be enabled, because we were only checking the user was not in the last page.
Now, we're checking the items prop to be present and equal to 0 to disable it in top of out existing checks. Therefore, merging this PR wouldn't affect any existing uses of the Pager without passing the items prop.
> Do not enable next page button if there are explicitly zero items.

- internal/docs/overview/examples/tables.js
Ray Bradbury's email is listed as "ray.asimov@gmail.com." This is incorrect.
> Fix typo in table docs example

- internal/docs/overview/examples/tables.js
via @smith 
> Ray Bradbury's email is listed as "ray.asimov@gmail.com." This is incorrect.
> Fix typo in table docs example (#1616)

- core/components/atoms/breadcrumb/breadcrumb.md
- core/components/atoms/breadcrumb/breadcrumb.tsx
Some changes to the Breadcrumb for better accessibility.
* Use `nav` instead of `div` for element
* Add `aria-label` to element
* Add docs about using `aria-current`
* Make `IBreadCrumbLinkProps` extend `ILinkProps`
Fixes #1289
Tested using [ChromeVox](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en), and seemed to have improved announcement.
This PR closes #1621
> Breadcrumb accessibility improvements

- core/components/atoms/breadcrumb/breadcrumb.md
- core/components/atoms/breadcrumb/breadcrumb.tsx
_via @smith_ 
* Use `nav` instead of `div` for element
* Add aria-label to element
* Add docs about using `aria-current`
* Make IBreadCrumbLinkProps extend ILinkProps
> Breadcrumb accessibility improvements (#1621)

- core/components/molecules/empty-state/empty-state.md
- core/components/molecules/empty-state/empty-state.story.tsx
- core/components/molecules/empty-state/empty-state.tsx
Add JSX support to `EmptyState`'s Title prop. This allows us to pass custom components as part of the Empty State titles like "Beta" tags.
> Add JSX support to EmptyState

- core/components/atoms/alert/alert.tsx
- internal/docs/component/prop-string.js
This PR addresses the syntax error currently rendered at https://auth0-cosmos.now.sh/docs/#/component/alert
The parsing in prop-string.js is handled by the default case, which wraps all values in `{}`-  breaking on string types. Added a ReactNode case to check the data type, similar to other cases. Considered extending the default case to handle multiple types, but opted for minimal changes to remove the error first.
Unit tests pass locally. 
No …
> Fix syntax error in the Alert component doc

- tooling/component-metadata.ts
When running the project in`docs.dev` or `metadata.dev` mode, the component count in the metadata.dev console warning increases with every recompile.
Moved the `warning` var into the function scope to fix.
No testing additions/updates needed. Fix applies to the development workflow only. Verified the count does not increase with subsequent recompilations.
- All active GitHub checks for tests, formatting, and security are passing
- The correct base branch …
> Reset count in console warning message on recompile

- core/components/atoms/select/select.md
- core/components/atoms/text-input/text-input.md
- core/components/atoms/textarea/textarea.md
- internal/docs/component/get-defaults-from-code.js
- internal/docs/component/prop-switcher.js
This PR addresses #1542 with 2 fixes:
* Updated markdown examples. Refactored props as defaults for any editable property to force prepopulating the value. Otherwise, any edit to an existing prop=value in the live code generates a duplicate (see https://auth0-cosmos.now.sh/docs/#/component/select and edit the `placeholder` prop).
* Hide the prop-type switcher for any union type that is not a string literal. Currently, all type unions are parsed as select options. See https://auth0-cosmos.now.sh/docs/#/component/select - `options` prop.
**Note**: Only updated a few markdown files with the defaults. Will update the rest after PR is approved.
Addresses issue #1542
No additional or updated tests needed - component functionality was not altered.
Manually tested: …
> Limit exposure of prop switching to string literal union types

- package.json
- tooling/component-metadata.ts
- yarn.lock
When running the `metadata.dev` script, any watched component or .md change triggers a full rebuild of `core/components/meta/metadata.json` that runs for several seconds, significantly delaying reload.
Improved rebuild performance on incremental changes by:
* Caching metadata and a hash for each file.
* Only scanning files matching a changed path (if passed).
* Refreshing cache with metadata related to individual file change.
* Rebuilding metadata.json from cached data.
Fixes apply to build/dev tooling. 
**Added dev dependency https://www.npmjs.com/package/md5-file. Will need to run `yarn` before testing.**
Can be manually tested by running the project in `docs.dev` mode and altering one of the component markdown files after the initial build.
- All active GitHub checks for tests, …
> Cache metadata for faster rebuilds in watch mode

- core/components/atoms/text/text.tsx
Make `<Text>` output consistent by always returning the same root element.
> Always use a span for Text

- core/components/atoms/alert/alert.tsx
- internal/docs/component/prop-string.js
_( Copied from #1636 )_
----------------------------
This PR addresses the syntax error currently rendered at https://auth0-cosmos.now.sh/docs/#/component/alert
The parsing in prop-string.js is handled by the default case, which wraps all values in `{}`-  breaking on string types. Added a ReactNode case to check the data type, similar to other cases. Considered extending the default case to handle multiple types, but opted for minimal changes to remove the error first.
Unit tests pass locally. 
No additional or updated tests needed - component functionality was not altered.
- Verified local build correctly renders the Alert example.
- All active GitHub checks for tests, formatting, and security are passing.
- The correct base branch is being used, if not `master`.
> Fix syntax error in the Alert component doc (#1636)

- core/components/layouts/row-layout/row-layout.md
Before: Combine the ColymnLayout with the RowLayout to achieve complex grid arrangments.
After: Combine the `ColumnLayout` with the `RowLayout` to achieve complex grid arrangements.
> Fix typo in row-layout.md

- core/components/atoms/file-input/file-input.story.tsx
- core/components/atoms/file-input/file-input.tsx
After removing a file from the files items list, the onChange event is not firing if you immediately try to re-add that file.
According to an entry in StackOverflow:
> File input cannot be controlled, there is no React specific way to do that.
The suggestion is to clear the input value like this:
```
e.target.value = null;
```
The best place to perform this action is before calling  `this.props.onChange` on the class method `onChangeHandler` and after …
> FileInput - Can't remove and add same file #1665

- core/components/molecules/form-group/form-group.tsx
- package.json
- yarn.lock
Simple fix for the extra rendering issue when sending and element such as null or undefined on a form group.
To test this fix, when creating a formGroup in the sandbox you can send null or an undefined element on it to check if they render.
> Extra rendering in formgroup fix

- core/components/atoms/select/select.tsx
On the server document my not be defined so we need to guard the reference inside of render.
Added a guarded reference to document.body since the document is not defined on the server during SSR.
> [DXDP-885] - Guard document.body reference in select component

- core/components/molecules/resource-list/resource-list.tsx
Guard the reference to document.querySelector since the document will not be defined on the server during SSR.
> [DXDP-886] Guard document.body reference in resource-list

- core/components/package.json
- core/components/styled.ts
- internal/test/unit/__snapshots__/select.test.tsx.snap
- yarn.lock
- Bump `styled-components` to 5.2 
- Export `ServerStyleSheet` from `styled-components`
Tested stoybook locally
> Bump styled components

- core/components/_helpers/story-example.tsx
- core/components/atoms/avatar/avatar.story.tsx
- core/components/atoms/avatar/avatar.tsx
- internal/test/unit/__snapshots__/avatar.test.tsx.snap
- internal/test/unit/avatar.test.tsx
We've identified an infinite loop in the Avatar component for when the `image` prop is not provided. In combination with bad `initials` or `email` props that end up failing to load, the following line get's HIT:
https://github.com/auth0/cosmos/blob/f96aaee5d6586a71d05c7a80b3cc2c003a4802eb/core/components/atoms/avatar/avatar.tsx#L143
You can notice that there is no handled case for when the Gravatar source has failed to load (except for the one in combination with image errors). This combination of events start an infinite loop of Line 143 being constantly hit, running several requests per second attempting indefinitely to load Gravatar again and again.
This is a bug which can cause systems to exhaust or block the user due to the excess of requests produced by the infinite loop.
There are …
> DXDP-1904 - Fixing Avatar component infinite loop when image not provided and gravatar fails to load

- core/components/atoms/tooltip/tooltip.tsx
- readme.md
Tooltip `width` value is currently causing unwanted truncating and breaking of tooltip content in Safari.
Removed the width property and retested.
**Before**
**After**
Also fixed some broken readme links.
> [ESD-11671] Fix tooltip wrapping in Safari, readme links
