auth0/cosmos

.travis.yml
package.json

Add empty travis file as placeholder

First travis build

---

src/components/atoms/input.js
src/components/atoms/textarea.js
src/components/atoms/typography.js
src/tokens/misc.js

- move line-height to global
- use spacing tokens for padding

Tokenise attributes for inputs

---

src/components/atoms/button.js
src/components/atoms/typography.js
src/tokens/fonts.js

Addresses [this comment](https://github.com/auth0/cosmos/pull/25#issuecomment-343185080)

Added Semibold typography and fixed font weight tokens

---

src/components/atoms/icon.js
src/index.js
src/manage/dummy-components.js
src/manage/index.js
src/overview/src/links.js
tooling/find-imports.js

Set up skeleton for manage PoC

---

package.json
tooling/component-metadata.js

Follow up for https://github.com/auth0/cosmos/pull/54

Make docs really live

---

tooling/component-metadata.js

Change matching pattern to `src/components/+(atoms|molecules)/*.js`

Add molecules to docs

---

package-lock.json
package.json
src/components/atoms/select.js
src/components/atoms/select.md
src/components/atoms/typography.js
src/components/index.js
src/components/molecules/form.js
src/docs/metadata.json
src/manage/settings.js
src/overview/src/forms.js

Add Select component

---

src/components/molecules/form.js

This addresses: https://github.com/auth0/cosmos/issues/66

Changed the form layout to % units and flexbox

---

src/components/atoms/button.js
src/components/molecules/form.js
src/docs/metadata.json
src/manage/settings.js
src/overview/src/buttons.js
src/tokens/colors.js

Add placeholder for destructive button

---

src/components/molecules/form.js

Add border on top for Form.Actions

---

package-lock.json
package.json

All js files will get prettierified before commiting 😎

Add precommit hook for prettier

---

src/overview/src/forms.js

Fix bug on overview with switch

---

src/components/_helpers/reset.js
src/components/atoms/_box.js
src/components/atoms/button.js
src/components/atoms/code.js
src/components/molecules/sidebar.js
src/docs/index.js
src/docs/spec/example-header.js
src/docs/spec/example.js
src/docs/spec/playground.js
src/docs/spec/props.js
src/manage/page.js
src/tokens/index.js

dev environment is clean and green now 😄

Fixed all eslint warnings

---

src/components/molecules/form/form.md

Document the use cases for form
Fields, FieldSet and Actions

Add documentation for forms

---

src/components/_helpers/pixel-calc.js
src/components/molecules/form/actions.js
src/components/molecules/form/divider.js
src/components/molecules/form/error.js
src/components/molecules/form/fieldset.js
src/components/molecules/form/form.md
src/components/molecules/form/index.js
src/components/molecules/form/label.js

Split forms into multiple files to keep things manageable

Split form further

---

src/components/molecules/form/form.md

Add some more text in form docs

---

package-lock.json
src/docs/sidebar/list.js
src/docs/spec/example.js
src/docs/spec/text-block.js

```diff
- molecules
+ Compound components
- atoms
+ Building blocks
```
+ Increase some spacing between paragraphs in docs

Change group name in sidebar + add more space

---

src/components/atoms/logo.md
src/components/atoms/textarea.js
src/components/atoms/textarea.md
src/components/index.js
src/docs/spec/playground.js
src/docs/spec/props.js
src/docs/spec/text-block.js

Add missing docs for logo and textarea
Extend `Input` to build textarea, fix some bugs.

Add missing docs for logo and textarea

---

src/components/molecules/form/description.js
src/manage/settings.js

Fix tiny bugs

---

src/components/atoms/empty-state.js
src/components/atoms/empty-state.md
src/components/atoms/icon.js
src/components/index.js
src/docs/spec/props.js
src/overview/index.js
src/overview/src/empty-states.js

Implement EmptyState component, add color property to Icon

---

src/components/molecules/tabs/content.js
src/components/molecules/tabs/index.js

separated tab content for @landitus 😄

now can style tab content

---

src/components/atoms/_styled-input/index.js
src/components/atoms/code/index.js
src/components/atoms/select/index.js
src/components/molecules/_action-input/index.js
src/components/molecules/form/description.js
src/components/molecules/form/index.js
src/components/molecules/form/label.js
src/components/molecules/tabs/index.js
src/components/molecules/tabs/link.js
src/manage/advanced.js
src/manage/client-list.js
src/manage/client.js
src/manage/connections.js
src/manage/page.js
src/manage/settings.js
src/tokens/colors.js
src/tokens/misc.js

I made some changes to colors, heights and elements to look as the do today in production code. This will help if we use it to test in an actual app, by blending in. It also gives us the opportunity to demo visual changes with our system tokens, as the new way to move forward with design changes. Not everything is 100% accurate to production, as some elements have been improved.
Still, buttons colors are broken as I didn't use tokens properly. I meant to wait for the merge of the tokens PR.

Dialed back on the design changes to reflect the actual design - Take 2

---

src/components/atoms/typography/index.js
src/components/index.js
src/components/molecules/list/index.js
src/components/molecules/list/list.md
src/components/molecules/stack/index.js
src/components/molecules/stack/stack.md
src/manage/client.js
src/manage/connections.js

Use this component to layout a list of components vertically

Add List component

---

src/manage/page.js

There were some old lint warnings for `manage/page.js`

Removed dead code = clean console

---

src/components/molecules/form/actions/index.js

Remove border and top padding, reduce margin

Roll back design of actions

---

src/components/molecules/form/actions/index.js

Removed the height CSS property

Removed unnecessary height in Form actions

---

src/components/atoms/button/button.md
src/components/molecules/form/field/field.md
src/components/molecules/form/form.md
src/docs/sidebar/link.js

- Changes the padding of the links in the sidebar
- Added Headings to the Form documentation to describe each example

Docs styles: better styles for sidebar and added headings to Form docs

---

src/components/atoms/switch/index.js
src/components/atoms/switch/switch.md

Switch is a controlled component, we need to handle prop changes after it's mounted
Fixes https://github.com/auth0/cosmos/issues/227
Bonus: changed alerts to console log in docs

Switch respects changes to on prop

---

tooling/component-metadata.js

(Code, Logo, etc)
Fixes https://github.com/auth0/cosmos/issues/229

Fixed sidebar link for components with no props

---

src/components/atoms/button/index.js

Copy by value not by reference 🙄
Fixes https://github.com/auth0/cosmos/issues/228

Button hover fix

---

src/components/molecules/form/actions/actions.md
src/components/molecules/form/actions/index.js

More details in https://github.com/auth0/cosmos/issues/239

Remove destructive from Form.Actions proptypes and docs

---

src/docs/spec/copy-button.js
src/docs/spec/playground.js

Fixes https://github.com/auth0/cosmos/issues/230

Docs: Add tooltip + feedback to copy code

---

src/overview/src/buttons.js
src/overview/src/container.js

Fixes https://github.com/auth0/cosmos/issues/235
```
```

Overview: clean up buttons

---

src/docs/spec/prop-conflicts.js
src/docs/spec/props.js

Add conflict handling for prop table

---

src/components/molecules/empty-state/empty-state.md
src/components/molecules/empty-state/index.js
src/overview/src/empty-states.js

Adjusted styles to make it look like the production code:

Styles adjustments for the Empty State

---

src/docs/spec/page-header.js

Fixes https://github.com/auth0/cosmos/issues/277

Fix wrapping of text in docs header

---

src/components/atoms/header/header.md
src/components/atoms/icon/icon.md
src/components/atoms/overlay/overlay.md
src/components/atoms/select/select.md
src/components/atoms/spinner/spinner.md
src/components/atoms/text-input/text-input.md
src/components/atoms/tooltip/tooltip.md
src/components/molecules/dialog/dialog.md
src/components/molecules/form-group/form-group.md

Added description for some too
Fixes https://github.com/auth0/cosmos/issues/276
Related: https://github.com/auth0/cosmos/issues/283

Add header for all components

---

src/manage/settings.js
src/overview/src/forms.js

... to have a closer-to-production-looking PoC

Removed ocurrences of the destructive action from the PoC

---

src/docs/docs-components/typography.js
src/docs/guiding-principles.js
src/docs/home.js
src/docs/index.js
src/docs/sidebar/index.js
src/docs/sidebar/list.js

Following up on https://github.com/auth0/cosmos/issues/65, it's a good idea to put the guiding principles on the docs 😉

Added the guiding principles to the docs

---

src/manage/client-list.js

Fix icon name in page header

---

src/components/atoms/header/header.md
src/components/atoms/header/index.js
src/components/molecules/list/index.js
src/overview/src/container.js
src/overview/src/typography.js

Fixes part of https://github.com/auth0/cosmos/issues/286

Removed h5, using h4 instead

---

src/components/atoms/header/index.js
src/components/molecules/page-header/index.js

Just add a split title to show in different page.
WDYT?
PS: "line-height normal on headings" will be added on new PR for safety and organization 😄

[PageHeader] Add a split title

---

src/manage/client-list.js
src/manage/connections.js

Hide label for switch in POC, right-align Switches and ButtonGroups

---

src/docs/spec/copy-button.js

Fixes https://github.com/auth0/cosmos/issues/309

Fixed copy code again

---

src/components/atoms/heading/index.js
src/components/atoms/paragraph/index.js
src/components/molecules/empty-state/index.js
src/components/molecules/list/index.js
src/components/molecules/page-header/index.js

Started to address https://github.com/auth0/cosmos/issues/315
Still I’ve commented where we need to override the margin inside some components

Added default line-height and margin to Headings

---

src/overview/examples/inputs.js
src/overview/index.js
src/overview/ov-components/example.js
src/overview/ov-components/overview.js

I just removed unused components. This keeps our code clean and without warnings in the browser console.

removed unused components

---

src/components/atoms/button/index.js
src/components/atoms/paragraph/index.js
src/components/atoms/switch/index.js
src/components/molecules/form/fieldset/divider.js
src/overview/examples/buttons.js
src/overview/examples/colors.js
src/overview/examples/forms.js
src/overview/examples/inputs.js
src/overview/examples/lists.js
src/overview/examples/logos.js
src/overview/examples/spacing.js
src/overview/examples/typography.js
src/overview/index.js
src/overview/ov-components/example.js
src/overview/ov-components/grid.js

- Done a few minor tweaks to the styles for Fieldset and Switch
- Added more components to the Overview page

Small tweaks for the PoC

---

src/components/molecules/page-header/index.js

minor fix for margin on page header

fix margin

---

src/components/molecules/tabs/link.js
src/tokens/colors.js

Tracking issue https://github.com/auth0/cosmos/issues/335

Change link color

---

src/overview/examples/page-headers.js

fix avatar image

---

src/components/molecules/_action-input/index.js

fix padding input text with icon

---

src/components/molecules/button-group/index.js
src/components/molecules/form/actions/index.js

tracking issue https://github.com/auth0/cosmos/issues/337

Fix form actions

---

src/icons/aliases.json

Add alias for rotate

---

contributing.md
src/docs/faqs.js
src/docs/home.js
src/docs/index.js
src/docs/sidebar/list.js

Feel free to add more questions and answers.
The idea is not to document all the questions, but the ones we get consistently from other teams. (if it's too long, it's painful to read)
questions i added: 
- When will cosmos be ready?
- What does versioning happen? How do I get updates?
- Why is cosmos from scratch instead of using an existing library?

Add page for FAQs

---

src/components/tokens.js
src/docs/docs-components/pre.js
src/docs/docs-components/tag.js
src/docs/docs-components/typography.js
src/docs/sidebar/group.js
src/docs/sidebar/index.js
src/docs/sidebar/link.js
src/docs/sidebar/list.js
src/docs/sidebar/logo.js
src/docs/sidebar/search.js
src/docs/spec/break.js
src/docs/spec/copy-button.js
src/docs/spec/icon-browser.js
src/docs/spec/playground.js
src/docs/spec/props.js
src/manage/client-avatar.js
src/manage/client-list.js
src/manage/components/top-navigation.js
src/manage/create-client-dialog.js
src/overview/examples/colors.js
src/overview/examples/lists.js
src/overview/examples/overlays.js
src/overview/examples/spacing.js
src/overview/ov-components/icon-sketch.js
src/overview/ov-components/navigation.js
src/overview/ov-components/stack.js
src/overview/src/container.js

components (= `auth0-cosmos`) imports `auth0-cosmos-tokens` and exposes it as `auth0-cosmos/tokens`

Expose tokens as part of cosmos

---

.travis.yml
deployment-package.json

now doesn't support yarn workspaces yet!
workaround: build on CI and then do a static deployment 🙈

attempt static deployments

---

src/manage/pages/clients/create-client-dialog.js

tracking https://github.com/auth0/cosmos/issues/380

update quickstart title to h4

---

src/components/atoms/avatar/avatar.md
src/components/atoms/avatar/index.js
src/components/index.js

tracking https://github.com/auth0/cosmos/issues/375

add avatar component

---

src/docs/faqs.js

fix emoji warning

---

src/components/molecules/button-group/index.js
src/components/molecules/form/actions/index.js

tracking https://github.com/auth0/cosmos/issues/388

Fix margin buttongroup

---

src/overview/examples/buttons.js
src/overview/src/buttons.js

Replace intent with appearance in overview

---

src/components/molecules/_action-input/index.js
src/components/molecules/form/actions/index.js
src/components/molecules/page-header/index.js

I missed a few cases of `Button` when moving things over to the new API! This patch fixes the remaining ones... hopefully. :)

Update missed components to new Button API

---

examples/webpack-hello-world/package.json
examples/webpack-hello-world/webpack.config.js
examples/webpack-hello-world/yarn.lock
src/components/babel.js
src/components/package.json
yarn.lock

```diff
- presets: ['babel-preset-cosmos']
+ presets: ['auth0-cosmos/babel']
```

nest preset inside cosmos/babel

---

src/components/atoms/text/index.js
src/components/index.js
src/manage/pages/clients/index.js
src/overview/examples/typography.js

Addresses: https://github.com/auth0/cosmos/issues/384

Created a Text component with 2 possible text styles

---

src/components/atoms/button/index.js
src/manage/pages/clients/create-client-dialog.js
src/manage/pages/clients/index.js
src/overview/ov-components/stack.js

Fix random bugs

---

Jenkinsfile

Reference: https://auth0team.atlassian.net/wiki/spaces/RM/pages/1736715/Jenkins+Pipelines+Quickstart
Used cibot on slack to create something: https://tools-jenkins-us-west-2.forge.auth0.net/job/cosmos/

Create jenkinsfile for release

---

src/components/molecules/empty-state/index.js

Now the main button in the Empty State is a cta button

Updated Empty States to use the CTA button

---

.travis.yml
package.json
yarn.lock

Fixes https://github.com/auth0/cosmos/issues/446
chromatic needs push events
now-cd needs pull_request events
¯\_(ツ)_/¯
I'm enabling both and making sure they don't fight 😛

Enable push events for travis

---

tooling/publish.js

Doh! Tokens need to transpiled as well!

Transpile tokens

---

.travis.yml
Jenkinsfile

Update jenkinsfile + alias

---

tooling/publish.js

Always publish all packages

---

package.json
src/docs/changes.js
tooling/publish.js

Version syncing should happen on release, not before that

sync versions to 0.0.6

---

package.json
src/components/codemods.js
src/components/package.json
tooling/catchup.js
tooling/publish.js

Removing codemods from the packages for now, we don't even need it

remove codemods

---

.gitignore
tooling/update-icons.js

Cleanup precommits

---

src/babel-preset/package.json
src/components/package.json
src/tokens/package.json
yarn.lock

last step for release
Run `yarn install` on your machines after this gets merged.

run yarn catchup for 0.1.1

---

src/components/atoms/paragraph/paragraph.story.js
src/components/atoms/select/select.story.js
src/components/atoms/spinner/spinner.story.js
src/components/atoms/switch/switch.story.js
src/components/atoms/text-input/text-input.story.js
src/components/atoms/text/index.js
src/components/atoms/text/text.story.js
src/components/atoms/textarea/text-area.story.js
src/components/atoms/thumbnail/thumbnail.story.js

- paragraph
- select
- spinner
- switch
- text
- text input
- text area
- thumbnail

More stories - part 3

---

src/index.js
src/manage/components/client-list.js
src/manage/components/page.js
src/manage/components/side-navigation.js
src/manage/components/top-navigation.js
src/manage/pages/client-detail/index.js
src/manage/pages/clients/index.js
src/manage/pages/emails/index.js
src/overview/examples/page-headers.js
src/overview/ov-components/navigation.js

Fixes https://github.com/auth0/cosmos/issues/502
Made the necessary changes and added a stub page for Email Templates to show the new URL structure.

Added the 'manage' slug to all PoC pages and links

---

src/components/atoms/button/index.js
src/components/atoms/icon/icon.story.js
src/components/atoms/icon/index.js
src/components/molecules/empty-state/empty-state.md
src/components/molecules/empty-state/index.js
src/overview/examples/empty-states.js
src/overview/examples/icons.js
src/overview/ov-components/navigation.js

Fixes: https://github.com/auth0/cosmos/issues/508
Fixed the style of the Learn More link to align properly and also added the small arrow.

Fixed style of Learn More link in Empty State

---

src/components/atoms/link/index.js
src/components/atoms/thumbnail/index.js
src/components/index.js
src/components/molecules/alert/alert.md
src/components/molecules/alert/index.js
src/components/molecules/resource-list/index.js
src/components/molecules/resource-list/item/index.js
src/components/molecules/resource-list/item/item.md
src/components/molecules/resource-list/resource-list.md
src/components/molecules/resource-list/resource-list.story.js
src/docs/spec/example.js
src/docs/spec/page-header.js
src/manage/components/client-list.js
src/overview/examples/resource-lists.js
src/overview/index.js
src/tokens/colors.js

This patch implements the beginning of the `ResourceList` component discussed in #394.
The documentation still needs to be improved, and I haven't replaced the existing implementation in Client List, but I wanted to share it to get feedback.

Add ResourceList and ResourceListItem components

---

changelog.md
package.json

This patch just adds to the changelog and increments the version to 0.2.0.

Update changelog and package.json for 0.2.0

---

src/components/molecules/resource-list/item/item.md
src/docs/docs-components/tag.js
src/docs/sidebar/link.js
src/docs/spec/default-props.js
src/docs/spec/props.js
tooling/component-metadata.js
tooling/get-metadata.js

Had to move type under description because it was getting crowded
Redesigned the sidebar label a little

Add defaults and * (required) to props table

---

src/babel-preset/package.json
src/components/package.json
src/tokens/package.json

catch up with 0.2.1

---

src/components/atoms/alert/alert.md
src/components/atoms/alert/index.js
src/components/index.js

Small improvements to alert component

---

src/components/molecules/form/actions/actions.js
src/components/molecules/form/form.md

Fixes https://github.com/auth0/cosmos/issues/541

Add bottom margin to Form.Actions

---

src/components/_helpers/reset.js

Reported on slack: https://auth0.slack.com/messages/C5ZK0DD8X/

Use tokens from absolute path in helpers

---

src/manage/components/page.js
src/manage/components/side-navigation.js
src/manage/components/welcome-card.js
src/manage/pages/welcome/customers-icon-e6580a660a.svg
src/manage/pages/welcome/index.js

The following is a POC to evaluate how a manage page can be built using cosmos components.
The expected result is the following:

POC for welcome page

---

changelog.md
package.json

Prepare 0.2.2

---

src/components/_helpers/action-shape.js
src/components/molecules/_action-input/_action-input.js
src/components/molecules/empty-state/empty-state.js
src/components/molecules/empty-state/empty-state.md
src/components/molecules/empty-state/empty-state.story.js
src/components/molecules/form/actions/actions.js
src/components/molecules/form/field/field.js
src/components/molecules/page-header/page-header.js
src/components/molecules/resource-list/item/item.js
src/components/molecules/resource-list/resource-list.js
src/docs/spec/prop-type.js
tooling/component-metadata.js

This also brings us one step closer to https://github.com/auth0/cosmos/issues/390

Standardise action shape

---

src/docs/sidebar/children.js

Resolves https://github.com/auth0/cosmos/issues/592

Avoid breaking docs site on specific searches

---

src/components/molecules/page-header/page-header.js
src/components/molecules/page-header/page-header.md

We forgot to update the propTypes

Update outdated proptypes for PageHeader

---

src/components/molecules/sidebar/sidebar-link-group.js
src/manage/components/side-navigation.js

Sidebar: open folder groups when child item is selected

---

src/components/molecules/stack/stack.js

Supersedes https://github.com/auth0/cosmos/pull/584

Stack space between by @nicogarcia

---

src/components/molecules/form/actions/actions.js
src/components/molecules/form/actions/actions.md
src/components/molecules/form/actions/actions.story.js

Document destructiveAction and only allow one at a time.

---

src/components/molecules/dialog/dialog.story.js

Add more stories to Dialog

---

examples/manage/components/page.js
examples/manage/components/side-navigation.js
examples/manage/components/welcome-card.js
examples/manage/pages/welcome/index.js
examples/manage/public/customer-icon.svg

@pbarrenechea Your pull request is revived here on top of master.

welcome page by @pbarrenechea (revive #560)

---

package-scripts.js
package.json

Realised chromatic is silently failing on master 😦 
Okay had to add some silly things to `package.json` so that chromatic doesn't complain. I've reported this as a bug to them and they've added it to their issue manager 😄

Give chromatic the right script

---

changelog.md
package.json

This patch also reformats the old entries to the changelog to follow the Added, Changed, Fixed convention.

Update changelog and bump version to 0.3.0

---

Jenkinsfile

I changed how scripts work but didn't update Jenkinsfile, my bad

Update Jenkinsfile for new deploy command

---

Jenkinsfile

Fixing tiny bug to make https://github.com/auth0/cosmos/pull/648 happen

Release 0.3.0 (again)

---

Jenkinsfile

Fix deploy command for reals this time

---

Jenkinsfile

typo 💀 
also changing slack target to design-system-int

Release 0.3.0 (attempt 3)

---

core/components/molecules/resource-list/item/item.js
core/components/molecules/resource-list/item/item.md

Support for ResourceListItem disabled actions

---

core/components/atoms/alert/alert.js
core/components/atoms/alert/alert.md
internal/docs/spec/prop-string.js

Fixes https://github.com/auth0/cosmos/issues/669
Added 3 new props and docs for them. Use the staging instance to play around with them
Not super sold on the names, suggestions welcome 😄 
```js
/** Allow user to dismiss this alert */
dismissible: PropTypes.bool, // default: true
/** Function to call on dismissal */
onDismiss: PropTypes.func,
/** Automatically dismiss after N seconds */
dismissAfterSeconds: PropTypes.number
```

Add dismissal features to alert

---

core/components/atoms/text-input/text-input.js

Default <input> to type=text

---

internal/docs/app.js

Supersedes https://github.com/auth0/cosmos/pull/663
Fixes https://github.com/auth0/cosmos/issues/644

Docs: Scroll to top on page change

---

core/components/styled.js

Conflicting exports were overriding each other
Reported by @nicogarcia 👍

Fix styled export

---

core/components/atoms/button/button.js
core/components/atoms/button/button.md
core/components/atoms/spinner/index.js
core/components/atoms/spinner/spinner.js

Fixes https://github.com/auth0/cosmos/issues/673

Support text in loading + success

---

core/components/molecules/form/field/field.js
core/components/molecules/form/label.js

Added conditionals to styles for form layouts to keep them from leaking to each other

---

core/components/atoms/badge/badge.js
core/components/atoms/label/label.js
core/components/atoms/tag/tag.js
core/components/molecules/pagination-toolbar/pagination-toolbar.js
core/components/molecules/table/table-header.js
core/components/molecules/table/table.js

This way it's fail proof
No specs changed 👌

use tokens from package

---

package.json
tooling/publish.js
yarn.lock

Change log isn't updated yet because releases after 0.3.0 are in beta

Draft 0.3.2-beta

---

.storybook/config.js
examples/manage/components/page.js
examples/manage/index.js
examples/manage/manage.story.js

This PR adds entire pages of our example application as stories for chromatic to run diffs over
This is an experiment, we'll know after a few PRs if this is the best or worst idea ever 😁
Pro: This way we can make sure we don't accidentally break the PoC without having to test the app
Con: This will need a review on every tiny change we do to any component
My motivation here is to bring our manage PoC closer to the real manage app by disabling resets and adding legacy styleguide. These tests should help!

Add Manage PoC to chromatic tests

---

core/components/atoms/button/button.js

https://github.com/auth0/cosmos/issues/692

fix bug with link appearance

---

examples/manage/pages/application-detail/index.js
internal/docs/overview/examples/tabs.js

Fix Tabs examples in Manage example app

Fix Tabs examples

---

examples/manage/components/page.js
examples/manage/index.js
examples/manage/manage.story.js
examples/manage/pages/application-detail/index.js

Fixes https://github.com/auth0/cosmos/issues/778
Needed to test https://github.com/auth0/cosmos/issues/732
Check out this [beautiful build](https://www.chromaticqa.com/build?appId=5aba7f6a07f95800202658ff&number=650)

Fix manage stories

---

core/components/atoms/button/button.js

Resolve https://github.com/auth0/cosmos/issues/675

added props for inverse option

---

core/components/atoms/button/button.js
core/components/atoms/button/stories/loading.story.js

Resolve https://github.com/auth0/cosmos/issues/811

Fix button with icon href

---

changelog.md
package.json

Prepare for 0.4.0

---

core/tokens/colors.js

Closes: https://github.com/auth0/cosmos/issues/765

Input color change in the tokens

---

core/babel-preset/package.json
core/components/package.json
core/engine/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/docs/package.json

```
$ yarn scripts deploy.catchup
```

Catchup with published version (0.4.0)

---

core/components/molecules/table/table.md

Replace avatar links with something more permanent

---

core/components/molecules/page-header/description.js

Fix #808: Fix learn more hover ignores the arrow icon

---

changelog.md
package.json

prepare for 0.5.0

---

changelog.md
package.json

Release 0.5.1

---

internal/docs/sidebar/index.js

Addresses https://github.com/auth0/cosmos/issues/887
**Before:**
**After:**

Added calculation for Fixed header for the sidebar content

---

core/components/_helpers/action-spacing.js
core/components/molecules/_action-input/_action-input.js
core/components/molecules/form/field/stories/text-field.story.js

Fixes https://github.com/auth0/cosmos/issues/838

Fix action margins

---

core/components/molecules/table/table.js
core/components/molecules/table/table.md
core/components/molecules/table/table.story.js

Reverts auth0/cosmos#859, this was not ready to merge as we were about to discuss the API for this change.

Revert "Add table loading indicator"

---

.github/PULL_REQUEST_TEMPLATE/bug_fix.md
.github/PULL_REQUEST_TEMPLATE/component_work.md

Add pull request templates

---

core/components/molecules/button-group/button-group.js
core/components/molecules/button-group/button-group.story.js

Fix button group margin on single button 

---

package-scripts.js

Running prettier on unstaged icons file after creating them, this should do the job

Fix pesky icons file bug

---

internal/docs/automation-glossary.js
internal/docs/contribution-guide.js

Closes #906 
~Need to merge #914 and rebase #915 from master to make tests pass here.~ Done

Testing guidelines

---

readme.md

README: change to absolute path

---

package-scripts.js

Chromatic: add auto-accept-changes-on-master

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/engine/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/docs/package.json

sync with deployed version

---

internal/docs/docs-components/version-switcher.js

Version switcher: Format the url correctly

---

core/components/_helpers/story-helpers.js
core/components/atoms/icon/icon.story.js

Add named icons story

---

internal/docs/sidebar/children.js
internal/docs/sidebar/index.js
internal/docs/sidebar/list.js

Fixed the bug in search, we should be good now.
As the list of guides has become long, search also filters them now

Docs: Fix component search + Search through guides

---

core/components/atoms/select/select.js
core/components/atoms/select/select.md
core/components/atoms/select/select.story.js
internal/test/snapshot/__snapshots__/select.test.js.snap
internal/test/unit/automation-attributes.test.js

Allow to have nothing selected on Select

---

core/components/atoms/select/select.story.js

Add placeholder story for select

---

package-scripts.js
package.json
tooling/update-icons.js
yarn.lock

This should take care of the pesky icons change in dev mode

Run prettier on generated icons

---

core/components/_helpers/default-prop-change.js
core/components/atoms/button/button.js
core/components/atoms/logo/logo.js
core/components/atoms/logo/logo.md
core/components/atoms/logo/logo.story.js
core/components/atoms/spinner/spinner.js
core/components/atoms/spinner/spinner.md
core/components/atoms/spinner/spinner.story.js
internal/test/snapshot/__snapshots__/breadcrumb.test.js.snap
internal/test/snapshot/__snapshots__/button.test.js.snap
internal/test/snapshot/__snapshots__/page-header.test.js.snap
internal/test/snapshot/__snapshots__/pager.test.js.snap
internal/test/snapshot/__snapshots__/pagination-toolbar.test.js.snap
internal/test/snapshot/__snapshots__/pagination.test.js.snap
internal/test/snapshot/__snapshots__/resource-list.test.js.snap
internal/test/snapshot/__snapshots__/sidebar.test.js.snap
internal/test/snapshot/__snapshots__/table.test.js.snap

New spinner variants

---

core/components/molecules/table/table.md

Add example for actions in table

---

core/components/molecules/table/table.md

Use avatar block for name fields in Table docs

---

core/components/molecules/table/table.js
core/components/molecules/table/table.md
core/components/molecules/table/table.story.js
internal/test/snapshot/__snapshots__/table.test.js.snap
internal/test/unit/__snapshots__/table.test.js.snap

Introduce table loading states

---

package-scripts.js

Fixes https://github.com/auth0/cosmos/issues/989

Hard coding chromatic app-code in package-scripts

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/engine/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/docs/package.json
package.json

Release 0.7.0

---

core/components/atoms/alert/alert.md

Carrying forward https://github.com/auth0/cosmos/pull/1009

Fix import statement in documentation by @ubenzer

---

changelog.md
package.json

Release 0.7.2

---

.github/PULL_REQUEST_TEMPLATE/component_work.md

I messed up #977 so I made a new pr

typo fixes in pr template

---

examples/webpack-hello-world/index.js

Changed the "Hello World" message to be less 1337.

Fix "Hello World" message

---

core/components/atoms/button/button.js

Fix safari button margins

---

internal/docs/app.js
internal/docs/sidebar/index.js

Fix sidebar scrolling in Firefox via @fer22f

---

core/components/molecules/list/list.js

This PR hopefully makes the list an unordered list instead of a group of divs

Makes the list HTML semantically correct

---

internal/docs/spec/page-header.js

Fixes https://github.com/auth0/cosmos/issues/696

Make Alert in docs non-dismissable

---

core/components/molecules/form/field/field.md
core/components/molecules/form/form.md

Form.Radio example does not work on docs
Fixes: https://github.com/auth0/cosmos/issues/839
[x] tests passes

Fix Form.Radio example does not working on docs

---

core/components/molecules/form/field/field.md
core/components/molecules/form/form.md

 Fix Form.Radio example does not working on docs vía @jvelezpo

---

examples/manage/pages/applications/create-application-dialog.js

Match dashboard standardization via @rkhoriander

---

core/components/_helpers/story-stack.js

Missing part of https://github.com/auth0/cosmos/pull/1044

remove line-height from story stack as well

---

core/components/_helpers/story-stack.js

Missed a spot in https://github.com/auth0/cosmos/pull/1046

Tests: stack item should inherit line height

---

core/components/molecules/pagination-toolbar/pagination-toolbar.js
core/components/molecules/pagination-toolbar/pagination-toolbar.story.js

Thanks to @astanciu for the fix
Added a story for tests

Pagination toolbar: Hide toolbar if there are zero items by @astanciu 

---

readme.md

Used quickstart guide and principles from docs website to improve README. Also corrected English and formatting.
Fixes #1036

Improve readme with material from docs website

---

.travis.yml
core/components/molecules/tabs/tabs.js
internal/test/unit/__snapshots__/tabs.test.js.snap

Make tabs accessible 

---

core/components/molecules/table/table.js
core/components/molecules/table/table.story.js

Table columns can now be passed as external children via @sanketsingh24

---

package.json
yarn.lock

Fixes https://github.com/auth0/cosmos/issues/976

Add nps-i to devDependencies

---

core/components/atoms/select/index.js
core/components/atoms/select/select.js
core/components/atoms/select/select.md
core/components/atoms/select/select.story.js

Select: Add disabled + disabled options + groups

---

core/components/atoms/_styled-input/_styled-input.js
core/components/atoms/text-input/text-input.js

Issue #1082 
I developed a way to have support for prepend and append content to Text Input.
One thing that I think it could be better is the code repetition, I tried @andresgalante  technique to redude code repetition, but it's a little bit complicated for me 😅 
Thank you
P.S: Something is wrong here, but I don't know what it is... Travis CI is and Chromatic are failling with errors, can someone help me?

#1082 Added support for prepend and append content to Text Input

---

internal/docs/app.js
internal/docs/sidebar/list.js
internal/docs/system-guidelines.js

This PR defines Cosmos guidelines.

Adds system guidelines to the docs

---

core/components/atoms/logo/logo.js
core/components/atoms/logo/logo.story.js

Revert "Add new logo variant"

---

core/components/molecules/table/table.story.js

Borrow tests from https://github.com/auth0/cosmos/pull/1101

Improve tests for table

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.8.1

---

package.json
yarn.lock

Remove if-env from dependencies

---

changelog.md
package.json

Release 0.9.1

---

core/components/atoms/button/stories/icon.story.js
core/components/molecules/table/table.story.js

Adding some test cases for #1164 to avoid regressions in the future
The bug was fixed in #1178

Add tests for #1164 

---

core/babel-preset/dev.js

Fixes https://github.com/auth0/cosmos/issues/166

Internal: Enable styled-components plugin for dev mode

---

core/components/atoms/paragraph/paragraph.story.js

This is handy to test out a Paragraph with styles for links, strong and code.

Added a paragraph story to test styles (link, strong, code)

---

internal/cosmos-scripts/package.json
package.json
yarn.lock

Tooling: Fix hot reload by @jvelezpo

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.9.2

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.9.3

---

core/components/molecules/page-header/description.js
core/components/molecules/page-header/page-header.js
core/components/molecules/page-header/page-header.md
internal/test/unit/__snapshots__/page-header.test.js.snap

This PR cleans up the PageHeader implementation, making it responsive and more flexible and maintainable for changes down the road.
It also adds a few comments on the documentation

Responsive PageHeader

---

core/components/atoms/select/select.js

Changes the color of the arrow icon of the Select component to be one of the allowed by the icon component.

Select arrow icon color fix

---

core/components/atoms/switch/switch.js

Switch.onToggle stopPropagation of event

---

core/components/package.json
yarn.lock

Just making it easier to jump to 4 in the future

upgrade to sc-3.latest

---

internal/docs/docs-components/folding-section.js

Fix https://github.com/auth0/cosmos/issues/1237

Docs: Fix folding section anchor

---

internal/docs/pages/contribution-guide/architecture.js
internal/docs/pages/contribution-guide/component-files.js
internal/docs/pages/contribution-guide/line-height.js
internal/docs/pages/contribution-guide/setup.js
internal/docs/pages/contribution-guide/system-guidelines.js
internal/docs/pages/contribution-guide/testing.js

The accordion was missing the page prop to properly function. So it should be fixed :) 
Still, I'm not sold on this UX, so I think we should go this route https://github.com/auth0/cosmos/issues/1245 once we merge this fix.

Fixed accordions in Contribution guide

---

examples/manage/components/application-list.js
examples/manage/package.json

Fix Security issue and fix error on example when opening Applications by @jvelezpo

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json
yarn.lock

Release 0.10.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.10.1

---

core/components/atoms/switch/switch.js

Added key to switch elements

---

core/components/atoms/switch/switch.js

Added key to switch elements by @tehsis (#1269)

---

core/components/molecules/resource-list/item/item.js

Test with playground:
```jsx
<ResourceList
items={[
{
title: 'Item 1',
subtitle: 'Native',
image:
'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDgiIGhlaWdodD0iNDgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBkPSJNMCAwaDQ4djQ4SDB6Ii8+PGcgZmlsbC1ydWxlPSJub256ZXJvIj48cGF0aCBkPSJNMjcuMjQ2IDM5SDEwLjc1NEExLjc1NCAxLjc1NCAwIDAgMSA5IDM3LjI0NlYyMC43NTRDOSAxOS43ODUgOS43ODUgMTkgMTAuNzU0IDE5aDE2LjQ5MmMuOTY5IDAgMS43NTQuNzg1IDEuNzU0IDEuNzU0djE2LjQ5MmMwIC45NjktLjc4NSAxLjc1NC0xLjc1NCAxLjc1NCIgZmlsbD0iIzE2MjE0RCIvPjxwYXRoIGQ9Ik0zMi4yNDYgMzRIMTUuNzU0QTEuNzU0IDEuNzU0IDAgMCAxIDE0IDMyLjI0NlYxNS43NTRjMC0uOTY5Ljc4NS0xLjc1NCAxLjc1NC0xLjc1NGgxNi40OTJjLjk2OSAwIDEuNzU0Ljc4NSAxLjc1NCAxLjc1NHYxNi40OTJjMCAuOTY5LS43ODUgMS43NTQtMS43NTQgMS43NTQiIGZpbGw9IiNFQzU0MjQiLz4 …
```

Fix button action onClick handler not including the item

---

internal/docs/docs-components/folding-section.js

Fixes https://github.com/auth0/cosmos/issues/1275

Docs: Fix broken folding links in contribution-guide

---

core/components/atoms/code/code.js
core/components/molecules/resource-list/item/item.js
core/components/molecules/resource-list/resource-list.md
core/components/molecules/resource-list/resource-list.story.js

This PR fixes #523 by cleaning up the resource list CSS.
It allows the first column to extend when there is no second column :)

Fixes Resource List columns

---

core/components/molecules/tabs/tabs.js
internal/docs/package.json
yarn.lock

Add `react-router-dom` dependency back to docs workspace

Fix react router dom dependency

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.11.0

---

changelog.md

Add list prefix to the changes list 🤦‍♂️

Fix changelog list

---

core/components/_helpers/width-string-prop-validator.js
core/components/molecules/resource-list/item/item.js
core/components/molecules/resource-list/resource-list.story.js

This PR adds a prop to set the width of the resource list body as requested by @hzalaz .
Since it's an open string 💩, I'd love for @siddharthkp to pitch in before merging it

Adds a prop to set the width to the resource list body

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.12.0

---

core/components/atoms/radio/radio.js
core/components/atoms/radio/radio.story.js
core/components/molecules/form/field/stories/radio-field.story.js
core/components/molecules/form/field/stories/radio.story.js

Fixes https://github.com/auth0/cosmos/issues/1394
Added missing stories for testing Radio and Form.Radio. Note that these tests don't look good because there's a visual regression, and are meant to be used to test the fix and to avoid future regressions.
I will approve the chromatic tests so we can merge.

Fixed rendering of label for Radio and Form.Radio (with tests)

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.12.1

---

changelog.md
package.json

Release 0.12.2

---

core/components/molecules/page-header/description.js
core/components/molecules/page-header/page-header.story.js

Fixed link hover styles in Page Header and improved story

---

core/components/molecules/form/field/field.js
core/components/molecules/form/field/stories/radio-field.story.js
internal/test/unit/__snapshots__/form-field.test.js.snap

This PR fixes #1410 by replacing the default value of the form label to be an empty string.

Replaces the default value of the form label to be an empty string

---

core/components/components.js
core/components/index.js
core/components/molecules/_gallery-layout/gallery-layout.js
core/components/molecules/_stack-layout/index.js
core/components/molecules/_stack-layout/stack-layout.js
core/components/molecules/_stack-layout/stack-layout.md
core/components/molecules/_stack-layout/stack-layout.story.js

@siddharthkp @landitus I really need your help with this one:
As you know `StackLayout` is a subset of flex and replaces `Stack`. Can you play with it, maybe create some stories and see how it behaves, and write your thoughts.
This I am looking to know are:
- Are we missing any option on the props? for example, distribution `space-between`
- Can you think of things you cannot build with this?
- Is the `space` prop clear enough after you use it? can you think of a better word?
@siddharthkp I'll also need your help to validate the `space` string. It should only accept numbers from 1 to 10, or the words `none` or `auto`.
Docs are missing, I am working on it today.
Thanks 🙏

Introduces Stack Layout

---

internal/docs/pages/contribution-guide.js
internal/docs/pages/contribution-guide/release-process.js

There's a lot of room for improvement, but n+1 > n 😄

Quick and dirty release guide

---

core/components/molecules/sidebar/sidebar-link-group.js

Update sidebar-link-group.js (#1420)

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.13.0

---

core/components/molecules/resource-list/item/item.js
core/components/molecules/resource-list/resource-list.js
internal/test/integration/helpers/event-handler.js
internal/test/integration/molecules/resource-list.fixture.js
internal/test/integration/molecules/resource-list.test.js
internal/test/unit/resource-list.test.js

Resolves #1442 
Resolves #1441

Fix undefined on onClick and onItemClick, onItemClick fired on onClick

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.14.0

---

core/components/_helpers/button-prop.js
core/components/molecules/page-header/page-header.js
core/components/molecules/page-header/page-header.md
core/components/molecules/page-header/page-header.story.js
internal/test/integration/molecules/page-header.fixture.js

Support buttons as actions in Page Header

---

core/components/atoms/alert/alert.js
core/components/atoms/text-input/text-input.js
core/components/atoms/textarea/textarea.js
core/components/molecules/avatar-block/avatar-block.js
core/components/molecules/empty-state/empty-state.js
internal/docs/spec/props.js
package.json
yarn.lock

Fixes https://github.com/auth0/cosmos/issues/1211

Docs: Add prop replacement right next to deprecated prop

---

core/components/atoms/tooltip/tooltip.js

Update Tooltip - Fix warning about popper.js

---

core/components/atoms/tooltip/tooltip.js

Update Tooltip (#1448)

---

core/components/molecules/_column-layout/column-layout.js
core/components/molecules/_column-layout/column-layout.story.js
core/components/molecules/_gallery-layout/gallery-layout.js
core/components/molecules/_gallery-layout/gallery-layout.story.js
core/components/molecules/_row-layout/row-layout.js
core/components/molecules/_row-layout/row-layout.story.js
core/components/molecules/_stack-layout/stack-layout.js
core/components/molecules/_stack-layout/stack-layout.story.js
core/tokens/spacing.js
examples/manage/pages/application-detail/index.js
examples/manage/pages/application-detail/settings.js
examples/manage/pages/applications/create-application-dialog.js
examples/manage/pages/applications/index.js

This PR closes https://github.com/auth0/cosmos/issues/1421 by adding new gutter sizes to the layouts.

Adds new sizes for gutters

---

core/components/atoms/checkbox/checkbox.js
core/components/atoms/checkbox/checkbox.story.js
core/components/atoms/radio/radio.js
core/components/atoms/radio/radio.story.js

via @m4tr1k
@andresgalante @francocorreasosa approved
* Fix checkbox when label is too long
* Changed const Label from p to div
* Fix radio when label is too long
* Added storybooks for checkbox and radio
* Add another test to checkbox

#1461 Fix checkbox when label is too long (#1462)

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.15.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.15.1

---

core/components/_helpers/globals.js
core/components/index.js
core/components/styled.js

This PR bugfixes previous solution and adds an export of ServerStyleSheet of the styles-components library

Go deeper on SSR solution

---

core/components/molecules/_column-layout/column-layout.js
core/components/molecules/_gallery-layout/gallery-layout.js
core/components/molecules/_row-layout/row-layout.js
core/components/molecules/_stack-layout/stack-layout.js
internal/docs/spec/icon-browser.js

Update gutter sizes prop-type

---

core/components/_helpers/width-string-prop-validator.js

Improve regular expression validator

Improve ResourceListItem body width validator

---

core/components/molecules/resource-list/resource-list.js

Check typeof function before calling it

Resource List: Add check for onItemClick

---

internal/docs/guides.js
internal/docs/pages/migration-guide.js

Staring a migration guide that we can keep adding to.
Let's merge this and add stuff as we go.

Start migration guide

---

core/components/molecules/sidebar/sidebar-link-group.js
core/components/molecules/sidebar/sidebar.story.js

Closes: https://github.com/auth0/cosmos/issues/1492

Fixed selected color for Link group and added basic stories

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.16.0

---

core/components/atoms/tooltip/tooltip.js

Apply tooltip fix from #1496 back

Apply z-index back to Tooltip Element

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.16.1

---

core/components/molecules/sidebar/sidebar-link-group.js
core/components/molecules/sidebar/sidebar.story.js

https://auth0-cosmos-franco-sidebar-props-fix.now.sh/sandbox/?selectedKind=Sidebar&selectedStory=interactive%20example&full=0&addons=1&stories=1&panelRight=0

Fix sidebar not changing styles when selected link prop changed

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.16.2

---

core/components/atoms/image/image.js

```diff
- <Image source="./image_url" />
+ <Image src="./image_url" />
```

Image API: support src instead

---

internal/docs/pages/contribution-guide.js
internal/docs/pages/contribution-guide/authoring-guides.js

One item from https://github.com/auth0/cosmos/issues/1507
See staging preview 👇

Docs: Tiny addition for authoring new guides

---

core/components/_helpers/avatar-url.js
core/components/atoms/avatar/avatar.js
core/components/atoms/image/image.js

Add image resolution failover to Avatar

---

internal/docs/pages/contribution-guide.js
internal/docs/pages/contribution-guide/build-pipeline.js

One item from #1507
See staging preview 👇

Docs: Document build pipeline

---

core/components/atoms/heading/heading.js
core/components/molecules/page-header/page-header.js
core/components/molecules/page-header/page-header.story.js

Support node in PageHeader title 

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.17.0

---

core/components/atoms/text-input/text-input.story.js
core/components/atoms/tooltip/action.js
core/components/atoms/tooltip/index.js
core/components/atoms/tooltip/tooltip.js
core/components/atoms/tooltip/tooltip.md

You can use a special variation of the tooltip which is made for input actions.
It does recieve a `content` object with the following keys:
- `default`: Is the default text to show in the tooltip (same as `content` in a normal tooltip).
- `loading`: Is the text will show if the child button `onClick` handler is an async function (Promise) while it's loading.
- `success`: Is the text will show when the `onClick` returns (if it's a sync function) or resolves (if it's async).
- `error`: If the text will show if the `onClick` is an async function and is rejected.
```jsx
<TextInput
type="text"
placeholder="Enter some text"
actions={[
<Tooltip.Action
content={{
default: 'Copy',
success: 'Copied!'
}}
>
<Button icon="copy" onClick={e => console.log(e)} />
</Tooltip.Action>,
<Tooltip.Action …
```

Tooltip for actions

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.18.0

---

package.json
yarn.lock

Update jest to fix security warning

---

core/components/atoms/select/select.js
core/components/atoms/select/select.story.js

[DXDP-175] Fix select's dialog overflow

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.19.0

---

core/components/atoms/select/select.js
core/components/atoms/select/select.md
core/components/atoms/select/select.story.js
internal/docs/component/prop-switcher.js
internal/test/unit/__snapshots__/select.test.js.snap
internal/test/unit/select.test.js

[DXDP-194] Async select support

---

core/components/atoms/select/select.md

Fixes the duplicate options in the docs.

---

core/components/molecules/empty-state/empty-state.js
core/components/molecules/empty-state/empty-state.md
core/components/molecules/empty-state/empty-state.story.js

[DXDP-201] Add Empty State variant without actions

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.20.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.20.1

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.20.2

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.20.3

---

core/components/atoms/select/select.js
core/components/atoms/select/select.story.js

```jsx
<Select
options={[
{ text: 'One', myCustomValue: 1 },
{ text: 'Two', myCustomValue: 2 },
{ text: 'Three', myCustomValue: 3 }
]}
value={value}
onChange={onChange}
getOptionValue={option => option.myCustomValue}
/>
```

Support getOptionValue in Select

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.21.0

---

core/components/molecules/navigation/navigation-item.js
core/components/molecules/navigation/navigation.story.js
internal/test/unit/__snapshots__/navigation.test.js.snap
internal/test/unit/navigation.test.js

plus use `shallow` instead of `render` in Navigation snapshot tests.

 Fix submenu not being open when subitem is selected 

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json
yarn.lock

Release 0.22.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.22.1

---

changelog.md
core/babel-preset/package.json
core/components/package.json
core/tokens/package.json
examples/manage/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.23.0

---

core/components/_helpers/list.js
core/components/molecules/list/list.js
core/components/molecules/list/list.story.js
internal/test/unit/helpers/list.test.js

Dynamic hidden list drawer actions

---

Jenkinsfile
changelog.md
core/babel-preset/package.json
core/components/atoms/alert/alert.tsx
core/components/molecules/avatar-block/avatar-block.tsx
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/docs-components/list.js
internal/docs/docs-components/tag.js
internal/docs/package.json
package.json
tooling/catchup.js
yarn.lock

> ⚠️ This PR encapsulates multiple releases to make Cosmos typings work with applications. Those versions are already released on NPM, this PR brings those changes to `master`.

TypeScript releases

---

changelog.md
core/babel-preset/package.json
core/components/atoms/text-input/text-input.tsx
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.23.9

---

changelog.md
core/babel-preset/package.json
core/components/molecules/sidebar/sidebar-link-group.tsx
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
internal/test/unit/__snapshots__/select.test.tsx.snap
package.json
yarn.lock

Release 0.23.10

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.23.11

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
internal/test/package.json
package.json
yarn.lock

Release 0.24.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.24.1

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.25.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.26.0

---

internal/docs/guides/contribution-guide/authoring-guides.js
internal/docs/guides/contribution-guide/build-pipeline.js
internal/docs/guides/contribution-guide/component-files.js
internal/docs/guides/contribution-guide/line-height.js
internal/docs/guides/contribution-guide/linking-cosmos.js
internal/docs/guides/contribution-guide/order-of-props.js
internal/docs/guides/contribution-guide/release-process.js
internal/docs/guides/contribution-guide/testing.js

While reading the contribution guideline for the first time, some things were unclear, and there were a few small typos. I tried to clarify things (e.g. components have files named <component_name>.tsx, not literally "component.tsx") and fix the odd typo.
Build the docs site and test it locally using the build in commands that appear with `yarn i`
- [N/A ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs

Small doc updates

---

internal/docs/guides/contribution-guide/authoring-guides.js
internal/docs/guides/contribution-guide/build-pipeline.js
internal/docs/guides/contribution-guide/component-files.js
internal/docs/guides/contribution-guide/line-height.js
internal/docs/guides/contribution-guide/linking-cosmos.js
internal/docs/guides/contribution-guide/order-of-props.js
internal/docs/guides/contribution-guide/release-process.js
internal/docs/guides/contribution-guide/testing.js

_(vía @CalRobert)_
* small doc update suggestions;
* move angle bracket to better indicate that file suffix is statix

Small doc updates (#1613)

---

internal/cosmos-scripts/package.json
yarn.lock

Docs dev site seems to run fine; not seeing anything broken.
Fixes #1440.

Update to latest webpack-dev-server

---

internal/cosmos-scripts/package.json
yarn.lock

via @smith 
> Fixes #1440. Docs dev site seems to run fine; not seeing anything broken.
Closes #1440

Update to latest webpack-dev-server (#1617)

---

.circleci/config.yml
Jenkinsfile

Update the versions of `NodeJS` and `Yarn` required to run in Jenkins & Circle CIs.

Update node & yarn versions

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json
yarn.lock

Release 0.27.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.28.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.29.0

---

core/components/molecules/form/field/stories/field.story.tsx

Added basic stories for the form field. These describe the different features: help text, help text with rich text, displaying errors and the different combinations.

Added plain examples of the Form field (with errors, help texts)

---

core/components/atoms/select/select.md
core/components/atoms/text-input/text-input.md
core/components/atoms/textarea/textarea.md
internal/docs/component/get-defaults-from-code.js
internal/docs/component/prop-switcher.js
package.json
tooling/component-metadata.ts
yarn.lock

(***via @pdillon***)
Closes #1542
--
Thank you @pdillon ❤️

Patrick Dillon contributions

---

core/components/atoms/file-input/file-input.md
core/components/atoms/file-input/file-input.story.tsx
core/components/atoms/file-input/file-input.tsx

Updates based on @hzalaz 's feedback:
- add 'accept' property on the IFileInputProps interface
- abstract onAttach and onDelete into onChange props method
- add a loading value for each file in the items array
+ updated storybook to reflect a file loading visual

Refactor file uploader

---

core/components/atoms/checkbox/checkbox.md

The current checkbox documentation does not offer additional examples for various uses of the component. This PR provides additional context to the documentation on the different component properties as well as the Checkbox Group layout.  
Jira: https://auth0team.atlassian.net/browse/DXDP-364
No additional tests have been added.

[DXDP-364] Checkbox documentation update

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.30.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.31.0

---

core/components/molecules/resource-list/resource-list.md
core/components/molecules/stack/stack.md

I don't really know how to deprecate a component, but I do know that I'd like to avoid usages of `Stack` and `ResourceList`.
So here is a small step :)

Adds deprecation text to the resource list and stack

---

core/components/atoms/file-input/file-input.tsx

Change '0 files selected' to 'No files selected' in FileInput atom

---

core/components/atoms/button/button.tsx

Before: Name of icon
After: Align Icon Left or Right

fix in button props comment

---

core/components/molecules/danger-zone/danger-zone.story.tsx
core/components/molecules/danger-zone/danger-zone.tsx

Adds an additional type option (React node) for the description Danger Zone item. This will allow additional information to be included into the description, like Links, for example.
Jira: https://auth0team.atlassian.net/browse/DXDP-709
Storybook testing

[DXDP-709] Danger Zone and React node for description

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.32.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.32.1

---

core/components/atoms/textarea/textarea.tsx

⚠️ Includes prettier changes (progressive)
Related to DXDP-817

Add `name`, `onBlur` and `onFocus` to TextArea

---

.prettierrc
core/components/atoms/_simple-select/simple-select.tsx
core/components/atoms/select/select.tsx
internal/test/unit/select.test.tsx

Actual additions in an isolated commit https://github.com/auth0/cosmos/pull/1693/commits/30495edb59b326ebe58e2c779ce47e98a20160a7

Add `onFocus` and `onBlur` to the Select component (simple and wrapper)

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release 0.33.0

---

core/components/molecules/form/field/field.md
core/components/molecules/form/field/field.tsx
core/components/molecules/form/field/stories/field.story.tsx

[DXDP-872] Implement "required" fields

---

core/components/atoms/_overlay/overlay.tsx

Moved portal element creation to componentDidMount. This will help open the door for SSR in the future.

[DXDP-884] - Move portal mount element creation to didMount

---

core/components/atoms/text-input/text-input.tsx

Fix: Deprecation notice in error prop comment

---

Jenkinsfile
changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release v0.36.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package-scripts.js
package.json

Release v0.36.1

---

core/components/atoms/_simple-select/simple-select.tsx
core/components/atoms/_styled-input/styled-input.ts
core/components/atoms/checkbox/checkbox.tsx
core/components/atoms/radio/radio.tsx
core/components/atoms/select/select.story.tsx
core/components/tokens/colors.ts
internal/test/unit/__snapshots__/select.test.tsx.snap

Updated read-only/disabled styles for the Select and Checkbox components.

[DXDP-1437] Update read-only checkbox and select styles

---

core/components/atoms/_input-with-actions/input-with-actions.tsx

This allows some items other than Buttons to be inside of the actions, but remain centered vertically. This will be needed to support the new button component.

Update Input actions to have align-items: center

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

Release v0.38.0

---

changelog.md
core/babel-preset/package.json
core/components/package.json
examples/perf-tests/package.json
examples/webpack-hello-world/package.json
internal/cosmos-scripts/package.json
internal/docs/package.json
package.json

- [] Merge PR to master
- [] Create a [new release on github](https://github.com/auth0/cosmos/releases)
- [] Delete stable branch on github

Release v0.38.1
